// AUTO-GENERATED by scripts/gen-kotlin-api.ts from src/api/*.ts (Zod schemas) — do not edit by
// hand. Regenerate via `npm run build`. See README.md "Releasing a new version".

package com.curio.contracts

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

@Serializable
public data class ApiError(
    val error: String,
)

@Serializable
public data class IdentifyRequest(
    val imagePaths: List<String>? = null,
    val imageUrls: List<String>? = null,
    val inlineImages: List<String>? = null,
    val taxonomyAspects: List<TaxonomyAspect>? = null,
    val imageHash: String? = null,
    val game: String? = null,
    val games: List<String>? = null,
    val ocrCardNumber: String? = null,
    val ocrSetCode: String? = null,
    val ocrSetName: String? = null,
    val ocrName: String? = null,
)

@Serializable
public data class TaxonomyAspect(
    val localizedAspectName: String,
    val aspectConstraint: AspectConstraint? = null,
    val aspectValues: List<AspectValue>? = null,
)

@Serializable
public data class AspectConstraint(
    val aspectMode: String? = null,
)

@Serializable
public data class AspectValue(
    val localizedValue: String,
)

@Serializable
public data class IdentifyResponse(
    val game: String,
    @SerialName("game_confidence") val gameConfidence: GameConfidence,
    @SerialName("game_low_confidence") val gameLowConfidence: Boolean,
    val name: String,
    @SerialName("set_name") val setName: String? = null,
    @SerialName("card_number") val cardNumber: String? = null,
    @SerialName("card_type") val cardType: String? = null,
    @SerialName("estimated_grade") val estimatedGrade: String,
    val confidence: GameConfidence,
    val attributes: List<String>,
    @SerialName("is_promo") val isPromo: Boolean,
    val language: String,
    val rarity: String? = null,
    @SerialName("image_roles") val imageRoles: ImageRoles,
    val flaws: List<Flaw>,
    @SerialName("field_sources") val fieldSources: Map<String, FieldSources>? = null,
    @SerialName("_api_usage") val apiUsage: ApiUsage? = null,
    val cached: Boolean? = null,
    val tier: Tier? = null,
    @SerialName("ai_call_avoided") val aiCallAvoided: Boolean? = null,
)

@Serializable(with = GameConfidenceSerializer::class)
public sealed interface GameConfidence {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object HIGH : GameConfidence {
        override val rawValue: String get() = "high"
    }
    public object MEDIUM : GameConfidence {
        override val rawValue: String get() = "medium"
    }
    public object LOW : GameConfidence {
        override val rawValue: String get() = "low"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : GameConfidence

    public companion object {
        public fun from(raw: String): GameConfidence = when (raw) {
            "high" -> HIGH
            "medium" -> MEDIUM
            "low" -> LOW
            else -> Unknown(raw)
        }
    }
}

public object GameConfidenceSerializer : KSerializer<GameConfidence> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("GameConfidence", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): GameConfidence = GameConfidence.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: GameConfidence) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ImageRoles(
    val front: Int,
    val back: Int? = null,
    val details: List<Int>,
)

@Serializable
public data class Flaw(
    val description: String,
    val region: String,
    val side: Side,
    val x: Double,
    val y: Double,
    val w: Double,
    val h: Double,
    val severity: Severity,
)

@Serializable(with = SideSerializer::class)
public sealed interface Side {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object FRONT : Side {
        override val rawValue: String get() = "front"
    }
    public object BACK : Side {
        override val rawValue: String get() = "back"
    }
    public object UNKNOWN : Side {
        override val rawValue: String get() = "unknown"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Side

    public companion object {
        public fun from(raw: String): Side = when (raw) {
            "front" -> FRONT
            "back" -> BACK
            "unknown" -> UNKNOWN
            else -> Unknown(raw)
        }
    }
}

public object SideSerializer : KSerializer<Side> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Side", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Side = Side.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Side) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = SeveritySerializer::class)
public sealed interface Severity {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object MINOR : Severity {
        override val rawValue: String get() = "minor"
    }
    public object MODERATE : Severity {
        override val rawValue: String get() = "moderate"
    }
    public object MAJOR : Severity {
        override val rawValue: String get() = "major"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Severity

    public companion object {
        public fun from(raw: String): Severity = when (raw) {
            "minor" -> MINOR
            "moderate" -> MODERATE
            "major" -> MAJOR
            else -> Unknown(raw)
        }
    }
}

public object SeveritySerializer : KSerializer<Severity> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Severity", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Severity = Severity.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Severity) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class FieldSources(
    val source: Source,
    val confidence: String? = null,
)

@Serializable(with = SourceSerializer::class)
public sealed interface Source {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object VISION : Source {
        override val rawValue: String get() = "vision"
    }
    public object SELLER : Source {
        override val rawValue: String get() = "seller"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Source

    public companion object {
        public fun from(raw: String): Source = when (raw) {
            "vision" -> VISION
            "seller" -> SELLER
            else -> Unknown(raw)
        }
    }
}

public object SourceSerializer : KSerializer<Source> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Source", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Source = Source.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Source) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ApiUsage(
    val model: Model,
    val escalated: Boolean,
    @SerialName("input_tokens") val inputTokens: Int,
    @SerialName("output_tokens") val outputTokens: Int,
    @SerialName("estimated_cost_usd") val estimatedCostUsd: Double,
    val cached: Boolean,
)

@Serializable(with = ModelSerializer::class)
public sealed interface Model {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object GPT_4O : Model {
        override val rawValue: String get() = "gpt-4o"
    }
    public object GPT_4O_MINI : Model {
        override val rawValue: String get() = "gpt-4o-mini"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Model

    public companion object {
        public fun from(raw: String): Model = when (raw) {
            "gpt-4o" -> GPT_4O
            "gpt-4o-mini" -> GPT_4O_MINI
            else -> Unknown(raw)
        }
    }
}

public object ModelSerializer : KSerializer<Model> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Model", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Model = Model.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Model) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = TierSerializer::class)
public sealed interface Tier {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object TIER0 : Tier {
        override val rawValue: String get() = "tier0"
    }
    public object VISION : Tier {
        override val rawValue: String get() = "vision"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Tier

    public companion object {
        public fun from(raw: String): Tier = when (raw) {
            "tier0" -> TIER0
            "vision" -> VISION
            else -> Unknown(raw)
        }
    }
}

public object TierSerializer : KSerializer<Tier> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Tier", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Tier = Tier.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Tier) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class IdentifyAmbiguousResponse(
    val tier: IdentifyAmbiguousTier,
    val candidates: List<IdentifyCandidate>,
)

@Serializable(with = IdentifyAmbiguousTierSerializer::class)
public sealed interface IdentifyAmbiguousTier {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object AMBIGUOUS : IdentifyAmbiguousTier {
        override val rawValue: String get() = "ambiguous"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : IdentifyAmbiguousTier

    public companion object {
        public fun from(raw: String): IdentifyAmbiguousTier = when (raw) {
            "ambiguous" -> AMBIGUOUS
            else -> Unknown(raw)
        }
    }
}

public object IdentifyAmbiguousTierSerializer : KSerializer<IdentifyAmbiguousTier> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("IdentifyAmbiguousTier", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): IdentifyAmbiguousTier = IdentifyAmbiguousTier.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: IdentifyAmbiguousTier) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class IdentifyCandidate(
    val game: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val nativeId: String,
)

@Serializable
public data class CaptureCommitRequest(
    val imagePaths: ImagePaths? = null,
    val imageUrls: ImageUrls? = null,
    val inlineImages: InlineImages? = null,
    val resolvedMatch: CatalogueLookupMatch? = null,
    val game: Game? = null,
    val ocr: Ocr? = null,
    val purchaseCost: Double? = null,
    val collectionType: CollectionType? = null,
    val shotQuality: List<ShotQualityDescriptor>? = null,
)

@Serializable
public data class ImagePaths(
    val front: String,
    val back: String,
    val details: List<Detail>? = null,
)

@Serializable
public data class Detail(
    val side: Side2? = null,
    val corner: String? = null,
    val region: String? = null,
    val path: String,
)

@Serializable(with = Side2Serializer::class)
public sealed interface Side2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object FRONT : Side2 {
        override val rawValue: String get() = "front"
    }
    public object BACK : Side2 {
        override val rawValue: String get() = "back"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Side2

    public companion object {
        public fun from(raw: String): Side2 = when (raw) {
            "front" -> FRONT
            "back" -> BACK
            else -> Unknown(raw)
        }
    }
}

public object Side2Serializer : KSerializer<Side2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Side2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Side2 = Side2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Side2) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ImageUrls(
    val front: String,
    val back: String,
    val details: List<Detail2>? = null,
)

@Serializable
public data class Detail2(
    val side: Side3? = null,
    val corner: String? = null,
    val region: String? = null,
    val url: String,
)

@Serializable(with = Side3Serializer::class)
public sealed interface Side3 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object FRONT : Side3 {
        override val rawValue: String get() = "front"
    }
    public object BACK : Side3 {
        override val rawValue: String get() = "back"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Side3

    public companion object {
        public fun from(raw: String): Side3 = when (raw) {
            "front" -> FRONT
            "back" -> BACK
            else -> Unknown(raw)
        }
    }
}

public object Side3Serializer : KSerializer<Side3> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Side3", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Side3 = Side3.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Side3) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class InlineImages(
    val front: String,
    val back: String,
    val details: List<Detail3>? = null,
)

@Serializable
public data class Detail3(
    val side: Side4? = null,
    val corner: String? = null,
    val dataUrl: String,
)

@Serializable(with = Side4Serializer::class)
public sealed interface Side4 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object FRONT : Side4 {
        override val rawValue: String get() = "front"
    }
    public object BACK : Side4 {
        override val rawValue: String get() = "back"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Side4

    public companion object {
        public fun from(raw: String): Side4 = when (raw) {
            "front" -> FRONT
            "back" -> BACK
            else -> Unknown(raw)
        }
    }
}

public object Side4Serializer : KSerializer<Side4> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Side4", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Side4 = Side4.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Side4) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class CatalogueLookupMatch(
    val game: Game? = null,
    val nativeId: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val rarity: String? = null,
    val language: String,
    val image: String? = null,
)

@Serializable(with = GameSerializer::class)
public sealed interface Game {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object POKEMON : Game {
        override val rawValue: String get() = "pokemon"
    }
    public object POKEMON_JP : Game {
        override val rawValue: String get() = "pokemon-jp"
    }
    public object MTG : Game {
        override val rawValue: String get() = "mtg"
    }
    public object YUGIOH : Game {
        override val rawValue: String get() = "yugioh"
    }
    public object LORCANA : Game {
        override val rawValue: String get() = "lorcana"
    }
    public object ONE_PIECE : Game {
        override val rawValue: String get() = "one-piece"
    }
    public object DIGIMON : Game {
        override val rawValue: String get() = "digimon"
    }
    public object DBS_FUSION : Game {
        override val rawValue: String get() = "dbs-fusion"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Game

    public companion object {
        public fun from(raw: String): Game = when (raw) {
            "pokemon" -> POKEMON
            "pokemon-jp" -> POKEMON_JP
            "mtg" -> MTG
            "yugioh" -> YUGIOH
            "lorcana" -> LORCANA
            "one-piece" -> ONE_PIECE
            "digimon" -> DIGIMON
            "dbs-fusion" -> DBS_FUSION
            else -> Unknown(raw)
        }
    }
}

public object GameSerializer : KSerializer<Game> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Game", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Game = Game.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Game) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class Ocr(
    val name: String? = null,
    val number: String? = null,
)

@Serializable(with = CollectionTypeSerializer::class)
public sealed interface CollectionType {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PERSONAL : CollectionType {
        override val rawValue: String get() = "personal"
    }
    public object RESALE : CollectionType {
        override val rawValue: String get() = "resale"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : CollectionType

    public companion object {
        public fun from(raw: String): CollectionType = when (raw) {
            "personal" -> PERSONAL
            "resale" -> RESALE
            else -> Unknown(raw)
        }
    }
}

public object CollectionTypeSerializer : KSerializer<CollectionType> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("CollectionType", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): CollectionType = CollectionType.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: CollectionType) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ShotQualityDescriptor(
    val side: Side5? = null,
    val corner: String? = null,
    val region: String? = null,
    val sharpness: Double? = null,
    val glare: Boolean? = null,
    val cropped: Boolean? = null,
    val skewDegrees: Double? = null,
    val orientation: Orientation? = null,
    val exposure: Exposure? = null,
    val centeringLR: Double? = null,
    val centeringTB: Double? = null,
)

@Serializable(with = Side5Serializer::class)
public sealed interface Side5 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object FRONT : Side5 {
        override val rawValue: String get() = "front"
    }
    public object BACK : Side5 {
        override val rawValue: String get() = "back"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Side5

    public companion object {
        public fun from(raw: String): Side5 = when (raw) {
            "front" -> FRONT
            "back" -> BACK
            else -> Unknown(raw)
        }
    }
}

public object Side5Serializer : KSerializer<Side5> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Side5", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Side5 = Side5.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Side5) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = OrientationSerializer::class)
public sealed interface Orientation {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object CORRECT : Orientation {
        override val rawValue: String get() = "correct"
    }
    public object ROTATED_90 : Orientation {
        override val rawValue: String get() = "rotated_90"
    }
    public object ROTATED_180 : Orientation {
        override val rawValue: String get() = "rotated_180"
    }
    public object ROTATED_270 : Orientation {
        override val rawValue: String get() = "rotated_270"
    }
    public object UNKNOWN : Orientation {
        override val rawValue: String get() = "unknown"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Orientation

    public companion object {
        public fun from(raw: String): Orientation = when (raw) {
            "correct" -> CORRECT
            "rotated_90" -> ROTATED_90
            "rotated_180" -> ROTATED_180
            "rotated_270" -> ROTATED_270
            "unknown" -> UNKNOWN
            else -> Unknown(raw)
        }
    }
}

public object OrientationSerializer : KSerializer<Orientation> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Orientation", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Orientation = Orientation.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Orientation) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = ExposureSerializer::class)
public sealed interface Exposure {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object UNDER : Exposure {
        override val rawValue: String get() = "under"
    }
    public object OVER : Exposure {
        override val rawValue: String get() = "over"
    }
    public object OK : Exposure {
        override val rawValue: String get() = "ok"
    }
    public object UNKNOWN : Exposure {
        override val rawValue: String get() = "unknown"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Exposure

    public companion object {
        public fun from(raw: String): Exposure = when (raw) {
            "under" -> UNDER
            "over" -> OVER
            "ok" -> OK
            "unknown" -> UNKNOWN
            else -> Unknown(raw)
        }
    }
}

public object ExposureSerializer : KSerializer<Exposure> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Exposure", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Exposure = Exposure.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Exposure) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class CaptureCommitResponse(
    val physicalCardId: String,
    val legacyCardId: String? = null,
    val game: String,
    val gameDisplayName: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val condition: String? = null,
    val rarity: String? = null,
    val suggestedPrice: Double? = null,
    val ebay: Ebay? = null,
    val subGrades: Map<String, JsonElement>? = null,
    val image: String? = null,
)

@Serializable
public data class Ebay(
    val low: Double? = null,
    val avg: Double? = null,
    val top: Double? = null,
)

@Serializable
public data class RecommendRequest(
    val physicalCardId: String,
    val isVintage: Boolean? = null,
    val pricingSettings: PricingSettings? = null,
)

@Serializable
public data class PricingSettings(
    val ebayFeeRate: Double,
    val ebayFeeFixed: Double,
    val packagingCost: Double,
    val shippingCost: Double,
    val taxRate: Double,
    val minProfitPct: Double,
    val minSaleValue: Double,
    val postageCost: Double,
)

@Serializable
public data class RecommendResponse(
    val route: RecommendedRoute,
    val alternatives: List<Alternative>,
    val economics: Economics,
    val assumptions: List<String>,
    val explanation: String,
    val confidence: GameConfidence,
    @SerialName("calculation_version") val calculationVersion: String,
    val physicalCardId: String,
    val currentRoute: RecommendedRoute? = null,
    val priceSource: String? = null,
    val priceConfidence: GameConfidence? = null,
    val currencyNote: String? = null,
    val gradeEV: Double? = null,
    val psa10PriceGbp: Double? = null,
    val p10: Double? = null,
    val p9: Double? = null,
    val gradingCostGbp: Double? = null,
    val rawNetGbp: Double? = null,
    val gradeEVConfidence: GradeEVConfidence? = null,
)

@Serializable(with = RecommendedRouteSerializer::class)
public sealed interface RecommendedRoute {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object LIST_SINGLE : RecommendedRoute {
        override val rawValue: String get() = "list_single"
    }
    public object BUNDLE : RecommendedRoute {
        override val rawValue: String get() = "bundle"
    }
    public object BULK : RecommendedRoute {
        override val rawValue: String get() = "bulk"
    }
    public object HOLD : RecommendedRoute {
        override val rawValue: String get() = "hold"
    }
    public object GRADE_REVIEW : RecommendedRoute {
        override val rawValue: String get() = "grade_review"
    }
    public object RESTORATION_REVIEW : RecommendedRoute {
        override val rawValue: String get() = "restoration_review"
    }
    public object DO_NOT_LIST : RecommendedRoute {
        override val rawValue: String get() = "do_not_list"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : RecommendedRoute

    public companion object {
        public fun from(raw: String): RecommendedRoute = when (raw) {
            "list_single" -> LIST_SINGLE
            "bundle" -> BUNDLE
            "bulk" -> BULK
            "hold" -> HOLD
            "grade_review" -> GRADE_REVIEW
            "restoration_review" -> RESTORATION_REVIEW
            "do_not_list" -> DO_NOT_LIST
            else -> Unknown(raw)
        }
    }
}

public object RecommendedRouteSerializer : KSerializer<RecommendedRoute> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("RecommendedRoute", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): RecommendedRoute = RecommendedRoute.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: RecommendedRoute) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class Alternative(
    val route: RecommendedRoute,
    @SerialName("expected_net_gbp") val expectedNetGbp: Double? = null,
    val why: String,
)

@Serializable
public data class Economics(
    @SerialName("expected_sale_gbp") val expectedSaleGbp: Double? = null,
    @SerialName("fees_gbp") val feesGbp: Double? = null,
    @SerialName("postage_gbp") val postageGbp: Double? = null,
    @SerialName("cost_basis_gbp") val costBasisGbp: Double? = null,
    @SerialName("expected_net_gbp") val expectedNetGbp: Double? = null,
    val liquidity: Liquidity? = null,
)

@Serializable(with = LiquiditySerializer::class)
public sealed interface Liquidity {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object HIGH : Liquidity {
        override val rawValue: String get() = "high"
    }
    public object MEDIUM : Liquidity {
        override val rawValue: String get() = "medium"
    }
    public object LOW : Liquidity {
        override val rawValue: String get() = "low"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Liquidity

    public companion object {
        public fun from(raw: String): Liquidity = when (raw) {
            "high" -> HIGH
            "medium" -> MEDIUM
            "low" -> LOW
            else -> Unknown(raw)
        }
    }
}

public object LiquiditySerializer : KSerializer<Liquidity> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Liquidity", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Liquidity = Liquidity.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Liquidity) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = GradeEVConfidenceSerializer::class)
public sealed interface GradeEVConfidence {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object MEDIUM : GradeEVConfidence {
        override val rawValue: String get() = "medium"
    }
    public object LOW : GradeEVConfidence {
        override val rawValue: String get() = "low"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : GradeEVConfidence

    public companion object {
        public fun from(raw: String): GradeEVConfidence = when (raw) {
            "medium" -> MEDIUM
            "low" -> LOW
            else -> Unknown(raw)
        }
    }
}

public object GradeEVConfidenceSerializer : KSerializer<GradeEVConfidence> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("GradeEVConfidence", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): GradeEVConfidence = GradeEVConfidence.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: GradeEVConfidence) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class RecommendBatchRequest(
    val cards: List<RecommendBatchCardInput>,
    val pricingSettings: PricingSettings? = null,
)

@Serializable
public data class RecommendBatchCardInput(
    val id: String,
    val avgGbp: Double? = null,
    val lowGbp: Double? = null,
    val topGbp: Double? = null,
    val priceSource: String? = null,
    val saleCount: Int? = null,
    val approxSaleCount: Boolean? = null,
    val condition: String? = null,
    val costBasis: Double? = null,
    val collectionType: CollectionType2? = null,
    val isVintage: Boolean? = null,
)

@Serializable(with = CollectionType2Serializer::class)
public sealed interface CollectionType2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PERSONAL : CollectionType2 {
        override val rawValue: String get() = "personal"
    }
    public object RESALE : CollectionType2 {
        override val rawValue: String get() = "resale"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : CollectionType2

    public companion object {
        public fun from(raw: String): CollectionType2 = when (raw) {
            "personal" -> PERSONAL
            "resale" -> RESALE
            else -> Unknown(raw)
        }
    }
}

public object CollectionType2Serializer : KSerializer<CollectionType2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("CollectionType2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): CollectionType2 = CollectionType2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: CollectionType2) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class RecommendBatchResponse(
    val results: List<RecommendBatchResult>,
)

@Serializable
public data class RecommendBatchResult(
    val id: String,
    val route: RecommendedRoute? = null,
    val alternatives: List<Alternative>,
    val economics: Economics? = null,
    val assumptions: List<String>,
    val explanation: String? = null,
    val confidence: GameConfidence? = null,
    @SerialName("calculation_version") val calculationVersion: String? = null,
    val priceSource: String? = null,
    val priceConfidence: GameConfidence? = null,
    val currencyNote: String? = null,
)

@Serializable
public data class CardSearchRequest(
    val q: String,
    val game: String? = null,
)

@Serializable
public data class CardSearchResponse(
    val results: List<CardSearchResult>,
)

@Serializable
public data class CardSearchResult(
    val tcgId: String,
    val name: String,
    val setName: String? = null,
    val number: String? = null,
    val rarity: String? = null,
    val image: String? = null,
    val marketGbp: Double? = null,
    val game: String? = null,
    val gameDisplayName: String? = null,
    val printingCount: Int? = null,
    val printings: List<Printing>? = null,
)

@Serializable
public data class Printing(
    val tcgId: String,
    val setName: String? = null,
    val number: String? = null,
    val rarity: String? = null,
    val image: String? = null,
    val marketGbp: Double? = null,
)

@Serializable
public data class PriceRequest(
    val name: String,
    @SerialName("set_name") val setName: String,
    @SerialName("card_number") val cardNumber: String,
    val condition: String? = null,
    @SerialName("tcg_id") val tcgId: String? = null,
    val tcgBaseline: TcgBaseline? = null,
    val noCache: Boolean? = null,
)

@Serializable
public data class TcgBaseline(
    @SerialName("tcp_market_usd") val tcpMarketUsd: Double? = null,
    @SerialName("cm_trend_eur") val cmTrendEur: Double? = null,
)

@Serializable
public data class PriceResponse(
    val low: Double? = null,
    val avg: Double? = null,
    val top: Double? = null,
    @SerialName("price_source") val priceSource: String? = null,
    val provider: String? = null,
    @SerialName("fx_rate") val fxRate: Double? = null,
    @SerialName("fx_date") val fxDate: String? = null,
    @SerialName("sale_count") val saleCount: Int? = null,
    @SerialName("approx_sale_count") val approxSaleCount: Boolean? = null,
    val comps: List<Map<String, JsonElement>>? = null,
    val confidence: GameConfidence? = null,
    @SerialName("price_warning") val priceWarning: String? = null,
    val cached: Boolean? = null,
    val stale: Boolean? = null,
    @SerialName("fetched_at") val fetchedAt: String? = null,
    val error: String? = null,
)

@Serializable
public data class CertLookupRequest(
    val grader: Grader,
    val certNumber: String,
)

@Serializable(with = GraderSerializer::class)
public sealed interface Grader {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PSA : Grader {
        override val rawValue: String get() = "PSA"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Grader

    public companion object {
        public fun from(raw: String): Grader = when (raw) {
            "PSA" -> PSA
            else -> Unknown(raw)
        }
    }
}

public object GraderSerializer : KSerializer<Grader> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Grader", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Grader = Grader.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Grader) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class CertLookupResponse(
    val found: Boolean,
    val grader: Grader2,
    val certNumber: String,
    val grade: String? = null,
    val gradeDescription: String? = null,
    val subject: String? = null,
    val year: String? = null,
    val brand: String? = null,
    val category: String? = null,
    val cardNumber: String? = null,
    val variety: String? = null,
    val labelType: String? = null,
)

@Serializable(with = Grader2Serializer::class)
public sealed interface Grader2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PSA : Grader2 {
        override val rawValue: String get() = "PSA"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Grader2

    public companion object {
        public fun from(raw: String): Grader2 = when (raw) {
            "PSA" -> PSA
            else -> Unknown(raw)
        }
    }
}

public object Grader2Serializer : KSerializer<Grader2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Grader2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Grader2 = Grader2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Grader2) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ChannelListingRequest(
    val channel: Channel,
    val cardRef: String,
    val priceGbp: Double,
    val condition: String,
)

@Serializable(with = ChannelSerializer::class)
public sealed interface Channel {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object CARDTRADER : Channel {
        override val rawValue: String get() = "cardtrader"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Channel

    public companion object {
        public fun from(raw: String): Channel = when (raw) {
            "cardtrader" -> CARDTRADER
            else -> Unknown(raw)
        }
    }
}

public object ChannelSerializer : KSerializer<Channel> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Channel", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Channel = Channel.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Channel) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ChannelListingResponse(
    val channel: Channel,
    val channelListingId: String? = null,
    val url: String? = null,
    val status: Status,
    val error: String? = null,
)

@Serializable(with = StatusSerializer::class)
public sealed interface Status {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object LISTED : Status {
        override val rawValue: String get() = "listed"
    }
    public object FAILED : Status {
        override val rawValue: String get() = "failed"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Status

    public companion object {
        public fun from(raw: String): Status = when (raw) {
            "listed" -> LISTED
            "failed" -> FAILED
            else -> Unknown(raw)
        }
    }
}

public object StatusSerializer : KSerializer<Status> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Status", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Status = Status.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Status) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class CatalogueLookupRequest(
    val game: Game? = null,
    val name: String? = null,
    val collectorNumber: String? = null,
    val setCode: String? = null,
)

@Serializable
public data class CatalogueLookupResponse(
    val match: CatalogueLookupMatch? = null,
    val confidence: GameConfidence? = null,
    val candidates: List<CatalogueLookupMatch> = emptyList(),
)

@Serializable
public data class Entitlement(
    val userId: String,
    val tier: Tier2,
    val status: Status2,
    val source: Source2,
    val currentPeriodEnd: String,
    val cancelAtPeriodEnd: Boolean,
    val trialEnd: String? = null,
    val updatedAt: String,
)

@Serializable(with = Tier2Serializer::class)
public sealed interface Tier2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object FREE : Tier2 {
        override val rawValue: String get() = "free"
    }
    public object STARTER : Tier2 {
        override val rawValue: String get() = "starter"
    }
    public object GROWTH : Tier2 {
        override val rawValue: String get() = "growth"
    }
    public object PRO : Tier2 {
        override val rawValue: String get() = "pro"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Tier2

    public companion object {
        public fun from(raw: String): Tier2 = when (raw) {
            "free" -> FREE
            "starter" -> STARTER
            "growth" -> GROWTH
            "pro" -> PRO
            else -> Unknown(raw)
        }
    }
}

public object Tier2Serializer : KSerializer<Tier2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Tier2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Tier2 = Tier2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Tier2) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = Status2Serializer::class)
public sealed interface Status2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object ACTIVE : Status2 {
        override val rawValue: String get() = "active"
    }
    public object TRIALING : Status2 {
        override val rawValue: String get() = "trialing"
    }
    public object PAST_DUE : Status2 {
        override val rawValue: String get() = "past_due"
    }
    public object GRACE : Status2 {
        override val rawValue: String get() = "grace"
    }
    public object CANCELED : Status2 {
        override val rawValue: String get() = "canceled"
    }
    public object EXPIRED : Status2 {
        override val rawValue: String get() = "expired"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Status2

    public companion object {
        public fun from(raw: String): Status2 = when (raw) {
            "active" -> ACTIVE
            "trialing" -> TRIALING
            "past_due" -> PAST_DUE
            "grace" -> GRACE
            "canceled" -> CANCELED
            "expired" -> EXPIRED
            else -> Unknown(raw)
        }
    }
}

public object Status2Serializer : KSerializer<Status2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Status2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Status2 = Status2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Status2) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = Source2Serializer::class)
public sealed interface Source2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object STRIPE : Source2 {
        override val rawValue: String get() = "stripe"
    }
    public object APPLE : Source2 {
        override val rawValue: String get() = "apple"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Source2

    public companion object {
        public fun from(raw: String): Source2 = when (raw) {
            "stripe" -> STRIPE
            "apple" -> APPLE
            else -> Unknown(raw)
        }
    }
}

public object Source2Serializer : KSerializer<Source2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Source2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Source2 = Source2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Source2) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class VerificationEventRequest(
    val physicalCardId: String,
    val kind: Kind,
    val field: String,
    val verdict: Verdict? = null,
    val previousValue: String? = null,
    val correctedValue: String? = null,
    val source: Source3? = null,
)

@Serializable(with = KindSerializer::class)
public sealed interface Kind {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object IDENTITY : Kind {
        override val rawValue: String get() = "identity"
    }
    public object CONDITION : Kind {
        override val rawValue: String get() = "condition"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Kind

    public companion object {
        public fun from(raw: String): Kind = when (raw) {
            "identity" -> IDENTITY
            "condition" -> CONDITION
            else -> Unknown(raw)
        }
    }
}

public object KindSerializer : KSerializer<Kind> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Kind", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Kind = Kind.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Kind) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = VerdictSerializer::class)
public sealed interface Verdict {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object CONFIRMED : Verdict {
        override val rawValue: String get() = "confirmed"
    }
    public object NOT_PRESENT : Verdict {
        override val rawValue: String get() = "not_present"
    }
    public object UNSURE : Verdict {
        override val rawValue: String get() = "unsure"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Verdict

    public companion object {
        public fun from(raw: String): Verdict = when (raw) {
            "confirmed" -> CONFIRMED
            "not_present" -> NOT_PRESENT
            "unsure" -> UNSURE
            else -> Unknown(raw)
        }
    }
}

public object VerdictSerializer : KSerializer<Verdict> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Verdict", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Verdict = Verdict.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Verdict) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = Source3Serializer::class)
public sealed interface Source3 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object IOS_CAPTURE : Source3 {
        override val rawValue: String get() = "ios_capture"
    }
    public object WEB_ADD_FLOW : Source3 {
        override val rawValue: String get() = "web_add_flow"
    }
    public object OTHER : Source3 {
        override val rawValue: String get() = "other"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Source3

    public companion object {
        public fun from(raw: String): Source3 = when (raw) {
            "ios_capture" -> IOS_CAPTURE
            "web_add_flow" -> WEB_ADD_FLOW
            "other" -> OTHER
            else -> Unknown(raw)
        }
    }
}

public object Source3Serializer : KSerializer<Source3> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Source3", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Source3 = Source3.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Source3) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class VerificationEventResponse(
    val recorded: Boolean,
    val id: String? = null,
)

@Serializable
public data class InspectionDepthHintRequest(
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val game: Game? = null,
    val tcgId: String? = null,
)

@Serializable
public data class InspectionDepthHintResponse(
    val depthTier: DepthTier,
    val rationale: String,
    val confidence: Confidence,
)

@Serializable(with = DepthTierSerializer::class)
public sealed interface DepthTier {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object MINIMAL : DepthTier {
        override val rawValue: String get() = "minimal"
    }
    public object STANDARD : DepthTier {
        override val rawValue: String get() = "standard"
    }
    public object THOROUGH : DepthTier {
        override val rawValue: String get() = "thorough"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : DepthTier

    public companion object {
        public fun from(raw: String): DepthTier = when (raw) {
            "minimal" -> MINIMAL
            "standard" -> STANDARD
            "thorough" -> THOROUGH
            else -> Unknown(raw)
        }
    }
}

public object DepthTierSerializer : KSerializer<DepthTier> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("DepthTier", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): DepthTier = DepthTier.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: DepthTier) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = ConfidenceSerializer::class)
public sealed interface Confidence {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object HIGH : Confidence {
        override val rawValue: String get() = "high"
    }
    public object MEDIUM : Confidence {
        override val rawValue: String get() = "medium"
    }
    public object LOW : Confidence {
        override val rawValue: String get() = "low"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Confidence

    public companion object {
        public fun from(raw: String): Confidence = when (raw) {
            "high" -> HIGH
            "medium" -> MEDIUM
            "low" -> LOW
            else -> Unknown(raw)
        }
    }
}

public object ConfidenceSerializer : KSerializer<Confidence> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Confidence", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Confidence = Confidence.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Confidence) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class SignedPhotoUrlRequest(
    val urls: List<String>,
    val ttlSeconds: Int? = null,
)

@Serializable
public data class SignedPhotoUrlResponse(
    val results: List<SignedPhotoUrlResult>,
)

@Serializable
public data class SignedPhotoUrlResult(
    val url: String,
    val signedUrl: String? = null,
    val error: String? = null,
)

@Serializable
public data class PricingRule(
    val id: String,
    val name: String,
    val active: Boolean,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val scopeCondition: List<String>,
    val conditionMultipliers: Map<String, Double>,
    val rounding: Rounding,
    val minPriceGbp: Double? = null,
    val maxPriceGbp: Double? = null,
    val createdAt: String,
    val updatedAt: String,
)

@Serializable(with = RoundingSerializer::class)
public sealed interface Rounding {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object NONE : Rounding {
        override val rawValue: String get() = "none"
    }
    public object NEAREST_10P : Rounding {
        override val rawValue: String get() = "nearest_10p"
    }
    public object NEAREST_50P : Rounding {
        override val rawValue: String get() = "nearest_50p"
    }
    public object NEAREST_POUND : Rounding {
        override val rawValue: String get() = "nearest_pound"
    }
    public object CHARM_99 : Rounding {
        override val rawValue: String get() = "charm_99"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Rounding

    public companion object {
        public fun from(raw: String): Rounding = when (raw) {
            "none" -> NONE
            "nearest_10p" -> NEAREST_10P
            "nearest_50p" -> NEAREST_50P
            "nearest_pound" -> NEAREST_POUND
            "charm_99" -> CHARM_99
            else -> Unknown(raw)
        }
    }
}

public object RoundingSerializer : KSerializer<Rounding> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Rounding", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Rounding = Rounding.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Rounding) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class PricingRuleInput(
    val name: String,
    val active: Boolean? = null,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val scopeCondition: List<String>,
    val conditionMultipliers: Map<String, Double>,
    val rounding: Rounding,
    val minPriceGbp: Double? = null,
    val maxPriceGbp: Double? = null,
)

@Serializable
public data class PricingRuleListResponse(
    val rules: List<PricingRule>,
)

@Serializable
public data class ListingTemplate(
    val id: String,
    val name: String,
    val active: Boolean,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val titlePattern: String,
    val descriptionPattern: String? = null,
    val createdAt: String,
    val updatedAt: String,
)

@Serializable
public data class ListingTemplateInput(
    val name: String,
    val active: Boolean? = null,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val titlePattern: String,
    val descriptionPattern: String? = null,
)

@Serializable
public data class ListingTemplateListResponse(
    val templates: List<ListingTemplate>,
)

@Serializable
public data class PricingBreakdownRequest(
    val price: Double,
    val purchaseCost: Double,
    val marketMedian: Double,
    val collectionType: CollectionType3? = null,
    val priceSource: String? = null,
    val settings: PricingSettings? = null,
)

@Serializable(with = CollectionType3Serializer::class)
public sealed interface CollectionType3 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PERSONAL : CollectionType3 {
        override val rawValue: String get() = "personal"
    }
    public object RESALE : CollectionType3 {
        override val rawValue: String get() = "resale"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : CollectionType3

    public companion object {
        public fun from(raw: String): CollectionType3 = when (raw) {
            "personal" -> PERSONAL
            "resale" -> RESALE
            else -> Unknown(raw)
        }
    }
}

public object CollectionType3Serializer : KSerializer<CollectionType3> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("CollectionType3", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): CollectionType3 = CollectionType3.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: CollectionType3) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class PricingBreakdownResponse(
    val purchaseCost: Double,
    val marketMedian: Double,
    val suggestedPrice: Double,
    val ebayFee: Double,
    val packagingCost: Double,
    val shippingCost: Double,
    val grossProfit: Double,
    val taxProvision: Double,
    val netProfit: Double,
    val netMarginPct: Double,
    val minViablePrice: Double,
    val isMarketBelowMin: Boolean,
    val warningMsg: String? = null,
    val priceKind: PriceKind,
)

@Serializable(with = PriceKindSerializer::class)
public sealed interface PriceKind {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object REALISED : PriceKind {
        override val rawValue: String get() = "realised"
    }
    public object ASKING : PriceKind {
        override val rawValue: String get() = "asking"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : PriceKind

    public companion object {
        public fun from(raw: String): PriceKind = when (raw) {
            "realised" -> REALISED
            "asking" -> ASKING
            else -> Unknown(raw)
        }
    }
}

public object PriceKindSerializer : KSerializer<PriceKind> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("PriceKind", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): PriceKind = PriceKind.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: PriceKind) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class ProfileResponse(
    val sellerType: SellerType,
    val sellerTypeSource: SellerTypeSource,
    val dispatchAddress: DispatchAddress,
    val agedInventoryDays: Int,
    val pricingSettings: StoredPricingSettings,
    val effectivePricingSettings: PricingSettings,
    val isAdmin: Boolean,
)

@Serializable(with = SellerTypeSerializer::class)
public sealed interface SellerType {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PRIVATE : SellerType {
        override val rawValue: String get() = "private"
    }
    public object BUSINESS : SellerType {
        override val rawValue: String get() = "business"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : SellerType

    public companion object {
        public fun from(raw: String): SellerType = when (raw) {
            "private" -> PRIVATE
            "business" -> BUSINESS
            else -> Unknown(raw)
        }
    }
}

public object SellerTypeSerializer : KSerializer<SellerType> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("SellerType", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): SellerType = SellerType.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: SellerType) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = SellerTypeSourceSerializer::class)
public sealed interface SellerTypeSource {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object MANUAL : SellerTypeSource {
        override val rawValue: String get() = "manual"
    }
    public object AUTO : SellerTypeSource {
        override val rawValue: String get() = "auto"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : SellerTypeSource

    public companion object {
        public fun from(raw: String): SellerTypeSource = when (raw) {
            "manual" -> MANUAL
            "auto" -> AUTO
            else -> Unknown(raw)
        }
    }
}

public object SellerTypeSourceSerializer : KSerializer<SellerTypeSource> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("SellerTypeSource", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): SellerTypeSource = SellerTypeSource.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: SellerTypeSource) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class DispatchAddress(
    val line1: String? = null,
    val city: String? = null,
    val postcode: String? = null,
    val country: String,
)

@Serializable
public data class StoredPricingSettings(
    val ebayFeeRate: Double? = null,
    val ebayFeeFixed: Double? = null,
    val packagingCost: Double,
    val shippingCost: Double,
    val taxRate: Double,
    val minProfitPct: Double,
    val minSaleValue: Double,
    val postageCost: Double,
)

@Serializable
public data class ProfilePatch(
    val sellerType: SellerType? = null,
    val dispatchAddress: DispatchAddressPatch? = null,
    val agedInventoryDays: Int? = null,
    val pricingSettings: StoredPricingSettingsPatch? = null,
)

@Serializable
public data class DispatchAddressPatch(
    val line1: String? = null,
    val city: String? = null,
    val postcode: String? = null,
    val country: String? = null,
)

@Serializable
public data class StoredPricingSettingsPatch(
    val ebayFeeRate: Double? = null,
    val ebayFeeFixed: Double? = null,
    val packagingCost: Double? = null,
    val shippingCost: Double? = null,
    val taxRate: Double? = null,
    val minProfitPct: Double? = null,
    val minSaleValue: Double? = null,
    val postageCost: Double? = null,
)

@Serializable
public data class DecideRequest(
    val physicalCardId: String? = null,
    val marketValueGbp: Double? = null,
    val condition: Condition? = null,
    val game: Game? = null,
    val isVintage: Boolean? = null,
    val collectionType: CollectionType4? = null,
    val targetMarginPct: Double? = null,
    val pricingSettings: PricingSettings? = null,
)

@Serializable(with = ConditionSerializer::class)
public sealed interface Condition {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object NM : Condition {
        override val rawValue: String get() = "NM"
    }
    public object LP : Condition {
        override val rawValue: String get() = "LP"
    }
    public object MP : Condition {
        override val rawValue: String get() = "MP"
    }
    public object HP : Condition {
        override val rawValue: String get() = "HP"
    }
    public object DMG : Condition {
        override val rawValue: String get() = "DMG"
    }
    public object GRADED : Condition {
        override val rawValue: String get() = "Graded"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : Condition

    public companion object {
        public fun from(raw: String): Condition = when (raw) {
            "NM" -> NM
            "LP" -> LP
            "MP" -> MP
            "HP" -> HP
            "DMG" -> DMG
            "Graded" -> GRADED
            else -> Unknown(raw)
        }
    }
}

public object ConditionSerializer : KSerializer<Condition> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Condition", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): Condition = Condition.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: Condition) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable(with = CollectionType4Serializer::class)
public sealed interface CollectionType4 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PERSONAL : CollectionType4 {
        override val rawValue: String get() = "personal"
    }
    public object RESALE : CollectionType4 {
        override val rawValue: String get() = "resale"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : CollectionType4

    public companion object {
        public fun from(raw: String): CollectionType4 = when (raw) {
            "personal" -> PERSONAL
            "resale" -> RESALE
            else -> Unknown(raw)
        }
    }
}

public object CollectionType4Serializer : KSerializer<CollectionType4> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("CollectionType4", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): CollectionType4 = CollectionType4.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: CollectionType4) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class DecideResponse(
    val decision: Decision,
    val price: PriceProvenance,
    val gradeEV: DecisionGradeEV? = null,
)

@Serializable
public data class Decision(
    val route: RecommendedRoute,
    val reason: RouteReason,
    val alternatives: List<DecisionAlternative> = emptyList(),
    val confidence: GameConfidence,
    val liquidity: Liquidity,
    val economics: DecisionEconomics,
    val maxBuyGbp: Double,
    val minAcceptGbp: Double,
    val offerPctAtMax: Double,
    val degraded: Boolean,
    val degradedReasons: List<DegradedReason> = emptyList(),
)

@Serializable(with = RouteReasonSerializer::class)
public sealed interface RouteReason {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object BELOW_BULK_FLOOR : RouteReason {
        override val rawValue: String get() = "below_bulk_floor"
    }
    public object NET_BELOW_MINIMUM : RouteReason {
        override val rawValue: String get() = "net_below_minimum"
    }
    public object GRADE_WORTH_REVIEWING : RouteReason {
        override val rawValue: String get() = "grade_worth_reviewing"
    }
    public object THIN_MARKET : RouteReason {
        override val rawValue: String get() = "thin_market"
    }
    public object BUNDLE_LOT_AVAILABLE : RouteReason {
        override val rawValue: String get() = "bundle_lot_available"
    }
    public object SOUND_SINGLE_LISTING : RouteReason {
        override val rawValue: String get() = "sound_single_listing"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : RouteReason

    public companion object {
        public fun from(raw: String): RouteReason = when (raw) {
            "below_bulk_floor" -> BELOW_BULK_FLOOR
            "net_below_minimum" -> NET_BELOW_MINIMUM
            "grade_worth_reviewing" -> GRADE_WORTH_REVIEWING
            "thin_market" -> THIN_MARKET
            "bundle_lot_available" -> BUNDLE_LOT_AVAILABLE
            "sound_single_listing" -> SOUND_SINGLE_LISTING
            else -> Unknown(raw)
        }
    }
}

public object RouteReasonSerializer : KSerializer<RouteReason> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("RouteReason", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): RouteReason = RouteReason.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: RouteReason) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class DecisionAlternative(
    val route: RecommendedRoute,
    val reason: AlternativeReason,
)

@Serializable(with = AlternativeReasonSerializer::class)
public sealed interface AlternativeReason {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object NET_NEGATIVE_AFTER_COSTS : AlternativeReason {
        override val rawValue: String get() = "net_negative_after_costs"
    }
    public object BUNDLE_SHARES_POSTAGE : AlternativeReason {
        override val rawValue: String get() = "bundle_shares_postage"
    }
    public object LIST_UNGRADED_INSTEAD : AlternativeReason {
        override val rawValue: String get() = "list_ungraded_instead"
    }
    public object LIST_NOW_ACCEPT_SLOWER : AlternativeReason {
        override val rawValue: String get() = "list_now_accept_slower"
    }
    public object LIST_ALONE_INSTEAD : AlternativeReason {
        override val rawValue: String get() = "list_alone_instead"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : AlternativeReason

    public companion object {
        public fun from(raw: String): AlternativeReason = when (raw) {
            "net_negative_after_costs" -> NET_NEGATIVE_AFTER_COSTS
            "bundle_shares_postage" -> BUNDLE_SHARES_POSTAGE
            "list_ungraded_instead" -> LIST_UNGRADED_INSTEAD
            "list_now_accept_slower" -> LIST_NOW_ACCEPT_SLOWER
            "list_alone_instead" -> LIST_ALONE_INSTEAD
            else -> Unknown(raw)
        }
    }
}

public object AlternativeReasonSerializer : KSerializer<AlternativeReason> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("AlternativeReason", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): AlternativeReason = AlternativeReason.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: AlternativeReason) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class DecisionEconomics(
    val marketValueGbp: Double,
    val feeGbp: Double,
    val postageGbp: Double,
    val packagingGbp: Double,
    val costBasisGbp: Double? = null,
    val taxProvisionGbp: Double,
    val expectedNetGbp: Double,
)

@Serializable(with = DegradedReasonSerializer::class)
public sealed interface DegradedReason {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object NO_SALE_COUNT : DegradedReason {
        override val rawValue: String get() = "no_sale_count"
    }
    public object FEES_UNKNOWN : DegradedReason {
        override val rawValue: String get() = "fees_unknown"
    }
    public object COMPATIBLE_COUNT_UNKNOWN : DegradedReason {
        override val rawValue: String get() = "compatible_count_unknown"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : DegradedReason

    public companion object {
        public fun from(raw: String): DegradedReason = when (raw) {
            "no_sale_count" -> NO_SALE_COUNT
            "fees_unknown" -> FEES_UNKNOWN
            "compatible_count_unknown" -> COMPATIBLE_COUNT_UNKNOWN
            else -> Unknown(raw)
        }
    }
}

public object DegradedReasonSerializer : KSerializer<DegradedReason> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("DegradedReason", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): DegradedReason = DegradedReason.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: DegradedReason) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class PriceProvenance(
    val source: String? = null,
    val confidence: GameConfidence? = null,
    val currencyNote: String? = null,
)

@Serializable
public data class DecisionGradeEV(
    val gradeEVGbp: Double? = null,
    val psa10PriceGbp: Double? = null,
    val p10: Double? = null,
    val p9: Double? = null,
    val gradingCostGbp: Double? = null,
    val rawNetGbp: Double? = null,
    val confidence: GradeEVConfidence? = null,
)

@Serializable
public data class DecideBatchRequest(
    val cards: List<DecideBatchCard>,
    val targetMarginPct: Double? = null,
    val pricingSettings: PricingSettings? = null,
)

@Serializable
public data class DecideBatchCard(
    val id: String,
    val marketValueGbp: Double? = null,
    val costBasisGbp: Double? = null,
    val condition: Condition? = null,
    val isVintage: Boolean? = null,
    val saleCount: Int? = null,
    val priceSource: String? = null,
    val compatibleCount: Int? = null,
    val collectionType: CollectionType5? = null,
)

@Serializable(with = CollectionType5Serializer::class)
public sealed interface CollectionType5 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object PERSONAL : CollectionType5 {
        override val rawValue: String get() = "personal"
    }
    public object RESALE : CollectionType5 {
        override val rawValue: String get() = "resale"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : CollectionType5

    public companion object {
        public fun from(raw: String): CollectionType5 = when (raw) {
            "personal" -> PERSONAL
            "resale" -> RESALE
            else -> Unknown(raw)
        }
    }
}

public object CollectionType5Serializer : KSerializer<CollectionType5> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("CollectionType5", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): CollectionType5 = CollectionType5.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: CollectionType5) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class DecideBatchResponse(
    val results: List<DecideBatchResult>,
)

@Serializable
public data class DecideBatchResult(
    val id: String,
    val decision: Decision? = null,
    val decisionUnavailable: DecisionUnavailable? = null,
    val price: PriceProvenance? = null,
)

@Serializable(with = DecisionUnavailableSerializer::class)
public sealed interface DecisionUnavailable {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object IDENTITY_UNRESOLVED : DecisionUnavailable {
        override val rawValue: String get() = "identity_unresolved"
    }
    public object NO_MARKET_VALUE : DecisionUnavailable {
        override val rawValue: String get() = "no_market_value"
    }
    public object PRICING_UNAVAILABLE : DecisionUnavailable {
        override val rawValue: String get() = "pricing_unavailable"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : DecisionUnavailable

    public companion object {
        public fun from(raw: String): DecisionUnavailable = when (raw) {
            "identity_unresolved" -> IDENTITY_UNRESOLVED
            "no_market_value" -> NO_MARKET_VALUE
            "pricing_unavailable" -> PRICING_UNAVAILABLE
            else -> Unknown(raw)
        }
    }
}

public object DecisionUnavailableSerializer : KSerializer<DecisionUnavailable> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("DecisionUnavailable", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): DecisionUnavailable = DecisionUnavailable.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: DecisionUnavailable) {
        encoder.encodeString(value.rawValue)
    }
}

@Serializable
public data class QuickScanRequest(
    val name: String? = null,
    val setName: String? = null,
    val cardNumber: String? = null,
    val setCode: String? = null,
    val game: Game? = null,
    val condition: Condition? = null,
    val finish: String? = null,
    val targetMarginPct: Double? = null,
)

@Serializable
public data class QuickScanResponse(
    val identified: Boolean,
    val candidates: List<QuickScanCandidate> = emptyList(),
    val match: QuickScanCandidate? = null,
    val decision: Decision? = null,
    val price: PriceProvenance? = null,
    val gradeEV: DecisionGradeEV? = null,
    val decisionUnavailable: DecisionUnavailable2? = null,
    val conditionAssessed: Boolean = false,
)

@Serializable
public data class QuickScanCandidate(
    val game: Game? = null,
    val nativeId: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val rarity: String? = null,
    val confidence: GameConfidence? = null,
    val image: String? = null,
)

@Serializable(with = DecisionUnavailable2Serializer::class)
public sealed interface DecisionUnavailable2 {
    /** The wire value. Present on every case INCLUDING Unknown, so a value this client does
     *  not recognise can still be round-tripped back unchanged rather than silently dropped. */
    public val rawValue: String

    public object IDENTITY_UNRESOLVED : DecisionUnavailable2 {
        override val rawValue: String get() = "identity_unresolved"
    }
    public object NO_MARKET_VALUE : DecisionUnavailable2 {
        override val rawValue: String get() = "no_market_value"
    }
    public object PRICING_UNAVAILABLE : DecisionUnavailable2 {
        override val rawValue: String get() = "pricing_unavailable"
    }

    /** A value this build does not know. Never originate one — see decisions/0027 item 2a. */
    public data class Unknown(override val rawValue: String) : DecisionUnavailable2

    public companion object {
        public fun from(raw: String): DecisionUnavailable2 = when (raw) {
            "identity_unresolved" -> IDENTITY_UNRESOLVED
            "no_market_value" -> NO_MARKET_VALUE
            "pricing_unavailable" -> PRICING_UNAVAILABLE
            else -> Unknown(raw)
        }
    }
}

public object DecisionUnavailable2Serializer : KSerializer<DecisionUnavailable2> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("DecisionUnavailable2", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): DecisionUnavailable2 = DecisionUnavailable2.from(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: DecisionUnavailable2) {
        encoder.encodeString(value.rawValue)
    }
}
