// AUTO-GENERATED by scripts/gen-kotlin-api.ts from src/api/*.ts (Zod schemas) — do not edit by
// hand. Regenerate via `npm run build`. See README.md "Releasing a new version".

package com.curio.contracts

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

@Serializable
public data class ApiError(
    val error: String,
)

@Serializable
public data class IdentifyRequest(
    val imagePaths: List<String>? = null,
    val imageUrls: List<String>? = null,
    val inlineImages: List<String>? = null,
    val taxonomyAspects: List<TaxonomyAspect>? = null,
    val imageHash: String? = null,
    val game: String? = null,
    val games: List<String>? = null,
    val ocrCardNumber: String? = null,
    val ocrSetCode: String? = null,
    val ocrSetName: String? = null,
    val ocrName: String? = null,
)

@Serializable
public data class TaxonomyAspect(
    val localizedAspectName: String,
    val aspectConstraint: AspectConstraint? = null,
    val aspectValues: List<AspectValue>? = null,
)

@Serializable
public data class AspectConstraint(
    val aspectMode: String? = null,
)

@Serializable
public data class AspectValue(
    val localizedValue: String,
)

@Serializable
public data class IdentifyResponse(
    val game: String,
    @SerialName("game_confidence") val gameConfidence: GameConfidence,
    @SerialName("game_low_confidence") val gameLowConfidence: Boolean,
    val name: String,
    @SerialName("set_name") val setName: String? = null,
    @SerialName("card_number") val cardNumber: String? = null,
    @SerialName("card_type") val cardType: String? = null,
    @SerialName("estimated_grade") val estimatedGrade: String,
    val confidence: GameConfidence,
    val attributes: List<String>,
    @SerialName("is_promo") val isPromo: Boolean,
    val language: String,
    val rarity: String? = null,
    @SerialName("image_roles") val imageRoles: ImageRoles,
    val flaws: List<Flaw>,
    @SerialName("field_sources") val fieldSources: Map<String, FieldSources>? = null,
    @SerialName("_api_usage") val apiUsage: ApiUsage? = null,
    val cached: Boolean? = null,
    val tier: Tier? = null,
    @SerialName("ai_call_avoided") val aiCallAvoided: Boolean? = null,
)

@Serializable
public enum class GameConfidence {
    @SerialName("high") HIGH,
    @SerialName("medium") MEDIUM,
    @SerialName("low") LOW;
}

@Serializable
public data class ImageRoles(
    val front: Int,
    val back: Int? = null,
    val details: List<Int>,
)

@Serializable
public data class Flaw(
    val description: String,
    val region: String,
    val side: Side,
    val x: Double,
    val y: Double,
    val w: Double,
    val h: Double,
    val severity: Severity,
)

@Serializable
public enum class Side {
    @SerialName("front") FRONT,
    @SerialName("back") BACK,
    @SerialName("unknown") UNKNOWN;
}

@Serializable
public enum class Severity {
    @SerialName("minor") MINOR,
    @SerialName("moderate") MODERATE,
    @SerialName("major") MAJOR;
}

@Serializable
public data class FieldSources(
    val source: Source,
    val confidence: String? = null,
)

@Serializable
public enum class Source {
    @SerialName("vision") VISION,
    @SerialName("seller") SELLER;
}

@Serializable
public data class ApiUsage(
    val model: Model,
    val escalated: Boolean,
    @SerialName("input_tokens") val inputTokens: Int,
    @SerialName("output_tokens") val outputTokens: Int,
    @SerialName("estimated_cost_usd") val estimatedCostUsd: Double,
    val cached: Boolean,
)

@Serializable
public enum class Model {
    @SerialName("gpt-4o") GPT_4O,
    @SerialName("gpt-4o-mini") GPT_4O_MINI;
}

@Serializable
public enum class Tier {
    @SerialName("tier0") TIER0,
    @SerialName("vision") VISION;
}

@Serializable
public data class IdentifyAmbiguousResponse(
    val tier: IdentifyAmbiguousTier,
    val candidates: List<IdentifyCandidate>,
)

@Serializable
public enum class IdentifyAmbiguousTier {
    @SerialName("ambiguous") AMBIGUOUS;
}

@Serializable
public data class IdentifyCandidate(
    val game: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val nativeId: String,
)

@Serializable
public data class CaptureCommitRequest(
    val imagePaths: ImagePaths? = null,
    val imageUrls: ImageUrls? = null,
    val inlineImages: InlineImages? = null,
    val resolvedMatch: CatalogueLookupMatch? = null,
    val game: Game? = null,
    val ocr: Ocr? = null,
    val purchaseCost: Double? = null,
    val collectionType: CollectionType? = null,
    val shotQuality: List<ShotQualityDescriptor>? = null,
)

@Serializable
public data class ImagePaths(
    val front: String,
    val back: String,
    val details: List<Detail>? = null,
)

@Serializable
public data class Detail(
    val side: Side2? = null,
    val corner: String? = null,
    val region: String? = null,
    val path: String,
)

@Serializable
public enum class Side2 {
    @SerialName("front") FRONT,
    @SerialName("back") BACK;
}

@Serializable
public data class ImageUrls(
    val front: String,
    val back: String,
    val details: List<Detail2>? = null,
)

@Serializable
public data class Detail2(
    val side: Side3? = null,
    val corner: String? = null,
    val region: String? = null,
    val url: String,
)

@Serializable
public enum class Side3 {
    @SerialName("front") FRONT,
    @SerialName("back") BACK;
}

@Serializable
public data class InlineImages(
    val front: String,
    val back: String,
    val details: List<Detail3>? = null,
)

@Serializable
public data class Detail3(
    val side: Side4? = null,
    val corner: String? = null,
    val dataUrl: String,
)

@Serializable
public enum class Side4 {
    @SerialName("front") FRONT,
    @SerialName("back") BACK;
}

@Serializable
public data class CatalogueLookupMatch(
    val game: Game? = null,
    val nativeId: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val rarity: String? = null,
    val language: String,
    val image: String? = null,
)

@Serializable
public enum class Game {
    @SerialName("pokemon") POKEMON,
    @SerialName("pokemon-jp") POKEMON_JP,
    @SerialName("mtg") MTG,
    @SerialName("yugioh") YUGIOH,
    @SerialName("lorcana") LORCANA,
    @SerialName("one-piece") ONE_PIECE,
    @SerialName("digimon") DIGIMON,
    @SerialName("dbs-fusion") DBS_FUSION;
}

@Serializable
public data class Ocr(
    val name: String? = null,
    val number: String? = null,
)

@Serializable
public enum class CollectionType {
    @SerialName("personal") PERSONAL,
    @SerialName("resale") RESALE;
}

@Serializable
public data class ShotQualityDescriptor(
    val side: Side5? = null,
    val corner: String? = null,
    val region: String? = null,
    val sharpness: Double? = null,
    val glare: Boolean? = null,
    val cropped: Boolean? = null,
    val skewDegrees: Double? = null,
    val orientation: Orientation? = null,
    val exposure: Exposure? = null,
    val centeringLR: Double? = null,
    val centeringTB: Double? = null,
)

@Serializable
public enum class Side5 {
    @SerialName("front") FRONT,
    @SerialName("back") BACK;
}

@Serializable
public enum class Orientation {
    @SerialName("correct") CORRECT,
    @SerialName("rotated_90") ROTATED_90,
    @SerialName("rotated_180") ROTATED_180,
    @SerialName("rotated_270") ROTATED_270,
    @SerialName("unknown") UNKNOWN;
}

@Serializable
public enum class Exposure {
    @SerialName("under") UNDER,
    @SerialName("over") OVER,
    @SerialName("ok") OK,
    @SerialName("unknown") UNKNOWN;
}

@Serializable
public data class CaptureCommitResponse(
    val physicalCardId: String,
    val legacyCardId: String? = null,
    val game: String,
    val gameDisplayName: String,
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val condition: String? = null,
    val rarity: String? = null,
    val suggestedPrice: Double? = null,
    val ebay: Ebay? = null,
    val subGrades: Map<String, JsonElement>? = null,
    val image: String? = null,
)

@Serializable
public data class Ebay(
    val low: Double? = null,
    val avg: Double? = null,
    val top: Double? = null,
)

@Serializable
public data class RecommendRequest(
    val physicalCardId: String,
    val isVintage: Boolean? = null,
    val pricingSettings: PricingSettings? = null,
)

@Serializable
public data class PricingSettings(
    val ebayFeeRate: Double,
    val ebayFeeFixed: Double,
    val packagingCost: Double,
    val shippingCost: Double,
    val taxRate: Double,
    val minProfitPct: Double,
    val minSaleValue: Double,
    val postageCost: Double,
)

@Serializable
public data class RecommendResponse(
    val route: RecommendedRoute,
    val alternatives: List<Alternative>,
    val economics: Economics,
    val assumptions: List<String>,
    val explanation: String,
    val confidence: GameConfidence,
    @SerialName("calculation_version") val calculationVersion: String,
    val physicalCardId: String,
    val currentRoute: RecommendedRoute? = null,
    val priceSource: String? = null,
    val priceConfidence: GameConfidence? = null,
    val currencyNote: String? = null,
    val gradeEV: Double? = null,
    val psa10PriceGbp: Double? = null,
    val p10: Double? = null,
    val p9: Double? = null,
    val gradingCostGbp: Double? = null,
    val rawNetGbp: Double? = null,
    val gradeEVConfidence: GradeEVConfidence? = null,
)

@Serializable
public enum class RecommendedRoute {
    @SerialName("list_single") LIST_SINGLE,
    @SerialName("bundle") BUNDLE,
    @SerialName("bulk") BULK,
    @SerialName("hold") HOLD,
    @SerialName("grade_review") GRADE_REVIEW,
    @SerialName("restoration_review") RESTORATION_REVIEW,
    @SerialName("do_not_list") DO_NOT_LIST;
}

@Serializable
public data class Alternative(
    val route: RecommendedRoute,
    @SerialName("expected_net_gbp") val expectedNetGbp: Double? = null,
    val why: String,
)

@Serializable
public data class Economics(
    @SerialName("expected_sale_gbp") val expectedSaleGbp: Double? = null,
    @SerialName("fees_gbp") val feesGbp: Double? = null,
    @SerialName("postage_gbp") val postageGbp: Double? = null,
    @SerialName("cost_basis_gbp") val costBasisGbp: Double? = null,
    @SerialName("expected_net_gbp") val expectedNetGbp: Double? = null,
    val liquidity: Liquidity? = null,
)

@Serializable
public enum class Liquidity {
    @SerialName("high") HIGH,
    @SerialName("medium") MEDIUM,
    @SerialName("low") LOW;
}

@Serializable
public enum class GradeEVConfidence {
    @SerialName("medium") MEDIUM,
    @SerialName("low") LOW;
}

@Serializable
public data class RecommendBatchRequest(
    val cards: List<RecommendBatchCardInput>,
    val pricingSettings: PricingSettings? = null,
)

@Serializable
public data class RecommendBatchCardInput(
    val id: String,
    val avgGbp: Double? = null,
    val lowGbp: Double? = null,
    val topGbp: Double? = null,
    val priceSource: String? = null,
    val saleCount: Int? = null,
    val approxSaleCount: Boolean? = null,
    val condition: String? = null,
    val costBasis: Double? = null,
    val collectionType: CollectionType2? = null,
    val isVintage: Boolean? = null,
)

@Serializable
public enum class CollectionType2 {
    @SerialName("personal") PERSONAL,
    @SerialName("resale") RESALE;
}

@Serializable
public data class RecommendBatchResponse(
    val results: List<RecommendBatchResult>,
)

@Serializable
public data class RecommendBatchResult(
    val id: String,
    val route: RecommendedRoute? = null,
    val alternatives: List<Alternative>,
    val economics: Economics? = null,
    val assumptions: List<String>,
    val explanation: String? = null,
    val confidence: GameConfidence? = null,
    @SerialName("calculation_version") val calculationVersion: String? = null,
    val priceSource: String? = null,
    val priceConfidence: GameConfidence? = null,
    val currencyNote: String? = null,
)

@Serializable
public data class CardSearchRequest(
    val q: String,
    val game: String? = null,
)

@Serializable
public data class CardSearchResponse(
    val results: List<CardSearchResult>,
)

@Serializable
public data class CardSearchResult(
    val tcgId: String,
    val name: String,
    val setName: String? = null,
    val number: String? = null,
    val rarity: String? = null,
    val image: String? = null,
    val marketGbp: Double? = null,
    val game: String? = null,
    val gameDisplayName: String? = null,
    val printingCount: Int? = null,
    val printings: List<Printing>? = null,
)

@Serializable
public data class Printing(
    val tcgId: String,
    val setName: String? = null,
    val number: String? = null,
    val rarity: String? = null,
    val image: String? = null,
    val marketGbp: Double? = null,
)

@Serializable
public data class PriceRequest(
    val name: String,
    @SerialName("set_name") val setName: String,
    @SerialName("card_number") val cardNumber: String,
    val condition: String? = null,
    @SerialName("tcg_id") val tcgId: String? = null,
    val tcgBaseline: TcgBaseline? = null,
    val noCache: Boolean? = null,
)

@Serializable
public data class TcgBaseline(
    @SerialName("tcp_market_usd") val tcpMarketUsd: Double? = null,
    @SerialName("cm_trend_eur") val cmTrendEur: Double? = null,
)

@Serializable
public data class PriceResponse(
    val low: Double? = null,
    val avg: Double? = null,
    val top: Double? = null,
    @SerialName("price_source") val priceSource: String? = null,
    val provider: String? = null,
    @SerialName("fx_rate") val fxRate: Double? = null,
    @SerialName("fx_date") val fxDate: String? = null,
    @SerialName("sale_count") val saleCount: Int? = null,
    @SerialName("approx_sale_count") val approxSaleCount: Boolean? = null,
    val comps: List<Map<String, JsonElement>>? = null,
    val confidence: GameConfidence? = null,
    @SerialName("price_warning") val priceWarning: String? = null,
    val cached: Boolean? = null,
    val stale: Boolean? = null,
    @SerialName("fetched_at") val fetchedAt: String? = null,
    val error: String? = null,
)

@Serializable
public data class CertLookupRequest(
    val grader: Grader,
    val certNumber: String,
)

@Serializable
public enum class Grader {
    @SerialName("PSA") PSA;
}

@Serializable
public data class CertLookupResponse(
    val found: Boolean,
    val grader: Grader2,
    val certNumber: String,
    val grade: String? = null,
    val gradeDescription: String? = null,
    val subject: String? = null,
    val year: String? = null,
    val brand: String? = null,
    val category: String? = null,
    val cardNumber: String? = null,
    val variety: String? = null,
    val labelType: String? = null,
)

@Serializable
public enum class Grader2 {
    @SerialName("PSA") PSA;
}

@Serializable
public data class ChannelListingRequest(
    val channel: Channel,
    val cardRef: String,
    val priceGbp: Double,
    val condition: String,
)

@Serializable
public enum class Channel {
    @SerialName("cardtrader") CARDTRADER;
}

@Serializable
public data class ChannelListingResponse(
    val channel: Channel,
    val channelListingId: String? = null,
    val url: String? = null,
    val status: Status,
    val error: String? = null,
)

@Serializable
public enum class Status {
    @SerialName("listed") LISTED,
    @SerialName("failed") FAILED;
}

@Serializable
public data class CatalogueLookupRequest(
    val game: Game? = null,
    val name: String? = null,
    val collectorNumber: String? = null,
    val setCode: String? = null,
)

@Serializable
public data class CatalogueLookupResponse(
    val match: CatalogueLookupMatch? = null,
    val confidence: GameConfidence? = null,
    val candidates: List<CatalogueLookupMatch>,
)

@Serializable
public data class Entitlement(
    val userId: String,
    val tier: Tier2,
    val status: Status2,
    val source: Source2,
    val currentPeriodEnd: String,
    val cancelAtPeriodEnd: Boolean,
    val trialEnd: String? = null,
    val updatedAt: String,
)

@Serializable
public enum class Tier2 {
    @SerialName("free") FREE,
    @SerialName("starter") STARTER,
    @SerialName("growth") GROWTH,
    @SerialName("pro") PRO;
}

@Serializable
public enum class Status2 {
    @SerialName("active") ACTIVE,
    @SerialName("trialing") TRIALING,
    @SerialName("past_due") PAST_DUE,
    @SerialName("grace") GRACE,
    @SerialName("canceled") CANCELED,
    @SerialName("expired") EXPIRED;
}

@Serializable
public enum class Source2 {
    @SerialName("stripe") STRIPE,
    @SerialName("apple") APPLE;
}

@Serializable
public data class VerificationEventRequest(
    val physicalCardId: String,
    val kind: Kind,
    val field: String,
    val verdict: Verdict? = null,
    val previousValue: String? = null,
    val correctedValue: String? = null,
    val source: Source3? = null,
)

@Serializable
public enum class Kind {
    @SerialName("identity") IDENTITY,
    @SerialName("condition") CONDITION;
}

@Serializable
public enum class Verdict {
    @SerialName("confirmed") CONFIRMED,
    @SerialName("not_present") NOT_PRESENT,
    @SerialName("unsure") UNSURE;
}

@Serializable
public enum class Source3 {
    @SerialName("ios_capture") IOS_CAPTURE,
    @SerialName("web_add_flow") WEB_ADD_FLOW,
    @SerialName("other") OTHER;
}

@Serializable
public data class VerificationEventResponse(
    val recorded: Boolean,
    val id: String? = null,
)

@Serializable
public data class InspectionDepthHintRequest(
    val name: String,
    val setName: String? = null,
    val cardNumber: String? = null,
    val game: Game? = null,
    val tcgId: String? = null,
)

@Serializable
public data class InspectionDepthHintResponse(
    val depthTier: DepthTier,
    val rationale: String,
    val confidence: Confidence,
)

@Serializable
public enum class DepthTier {
    @SerialName("minimal") MINIMAL,
    @SerialName("standard") STANDARD,
    @SerialName("thorough") THOROUGH;
}

@Serializable
public enum class Confidence {
    @SerialName("high") HIGH,
    @SerialName("medium") MEDIUM,
    @SerialName("low") LOW;
}

@Serializable
public data class SignedPhotoUrlRequest(
    val urls: List<String>,
    val ttlSeconds: Int? = null,
)

@Serializable
public data class SignedPhotoUrlResponse(
    val results: List<SignedPhotoUrlResult>,
)

@Serializable
public data class SignedPhotoUrlResult(
    val url: String,
    val signedUrl: String? = null,
    val error: String? = null,
)

@Serializable
public data class PricingRule(
    val id: String,
    val name: String,
    val active: Boolean,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val scopeCondition: List<String>,
    val conditionMultipliers: Map<String, Double>,
    val rounding: Rounding,
    val minPriceGbp: Double? = null,
    val maxPriceGbp: Double? = null,
    val createdAt: String,
    val updatedAt: String,
)

@Serializable
public enum class Rounding {
    @SerialName("none") NONE,
    @SerialName("nearest_10p") NEAREST_10P,
    @SerialName("nearest_50p") NEAREST_50P,
    @SerialName("nearest_pound") NEAREST_POUND,
    @SerialName("charm_99") CHARM_99;
}

@Serializable
public data class PricingRuleInput(
    val name: String,
    val active: Boolean? = null,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val scopeCondition: List<String>,
    val conditionMultipliers: Map<String, Double>,
    val rounding: Rounding,
    val minPriceGbp: Double? = null,
    val maxPriceGbp: Double? = null,
)

@Serializable
public data class PricingRuleListResponse(
    val rules: List<PricingRule>,
)

@Serializable
public data class ListingTemplate(
    val id: String,
    val name: String,
    val active: Boolean,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val titlePattern: String,
    val descriptionPattern: String? = null,
    val createdAt: String,
    val updatedAt: String,
)

@Serializable
public data class ListingTemplateInput(
    val name: String,
    val active: Boolean? = null,
    val scopeGame: List<String>,
    val scopeSet: List<String>,
    val titlePattern: String,
    val descriptionPattern: String? = null,
)

@Serializable
public data class ListingTemplateListResponse(
    val templates: List<ListingTemplate>,
)

@Serializable
public data class PricingBreakdownRequest(
    val price: Double,
    val purchaseCost: Double,
    val marketMedian: Double,
    val collectionType: CollectionType3? = null,
    val priceSource: String? = null,
    val settings: PricingSettings? = null,
)

@Serializable
public enum class CollectionType3 {
    @SerialName("personal") PERSONAL,
    @SerialName("resale") RESALE;
}

@Serializable
public data class PricingBreakdownResponse(
    val purchaseCost: Double,
    val marketMedian: Double,
    val suggestedPrice: Double,
    val ebayFee: Double,
    val packagingCost: Double,
    val shippingCost: Double,
    val grossProfit: Double,
    val taxProvision: Double,
    val netProfit: Double,
    val netMarginPct: Double,
    val minViablePrice: Double,
    val isMarketBelowMin: Boolean,
    val warningMsg: String? = null,
    val priceKind: PriceKind,
)

@Serializable
public enum class PriceKind {
    @SerialName("realised") REALISED,
    @SerialName("asking") ASKING;
}
