// AUTO-GENERATED by scripts/gen-kotlin-db.ts from src/db/database.types.ts — do not edit by
// hand. Regenerate via `npm run build`. See README.md "Releasing a new version".

package com.curio.contracts

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

/** Row shape for `public.audit_events`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class AuditEventsRow(
    @SerialName("account_id") val accountId: String? = null,
    @SerialName("created_at") val createdAt: String,
    @SerialName("entity_id") val entityId: String,
    @SerialName("entity_type") val entityType: String,
    @SerialName("event_type") val eventType: String,
    val id: String,
    val payload: JsonElement,
    @SerialName("user_agent") val userAgent: String? = null,
)

/** Row shape for `public.catalogue_cards`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class CatalogueCardsRow(
    val attributes: List<String>,
    @SerialName("card_number") val cardNumber: String? = null,
    @SerialName("created_at") val createdAt: String,
    val finishes: List<String>,
    val game: String,
    val id: String,
    @SerialName("image_ref") val imageRef: String? = null,
    @SerialName("is_promo") val isPromo: Boolean,
    val language: String,
    @SerialName("listing_desc_template") val listingDescTemplate: String? = null,
    @SerialName("listing_title_template") val listingTitleTemplate: String? = null,
    val name: String,
    @SerialName("name_confidence") val nameConfidence: Double? = null,
    @SerialName("native_catalogue_id") val nativeCatalogueId: String? = null,
    @SerialName("normalized_name") val normalizedName: String? = null,
    @SerialName("normalized_number") val normalizedNumber: String? = null,
    val rarity: String? = null,
    @SerialName("scryfall_id") val scryfallId: String? = null,
    @SerialName("set_confidence") val setConfidence: Double? = null,
    @SerialName("set_name") val setName: String? = null,
    val source: String? = null,
    @SerialName("tcg_id") val tcgId: String? = null,
    @SerialName("tcgplayer_id") val tcgplayerId: String? = null,
    @SerialName("updated_at") val updatedAt: String,
    @SerialName("verified_at") val verifiedAt: String? = null,
)

/** Row shape for `public.catalogue_sets`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class CatalogueSetsRow(
    @SerialName("card_count") val cardCount: Int? = null,
    val game: String,
    val id: String,
    @SerialName("ingested_at") val ingestedAt: String,
    @SerialName("set_code") val setCode: String,
    @SerialName("set_name") val setName: String,
    val source: String,
)

/** Row shape for `public.condition_assessments`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class ConditionAssessmentsRow(
    @SerialName("assessment_version") val assessmentVersion: Int,
    @SerialName("centering_ratios") val centeringRatios: JsonElement? = null,
    val confidence: String? = null,
    @SerialName("created_at") val createdAt: String,
    val defects: JsonElement,
    val id: String,
    @SerialName("image_quality") val imageQuality: JsonElement? = null,
    @SerialName("is_current") val isCurrent: Boolean,
    @SerialName("model_version") val modelVersion: String? = null,
    @SerialName("physical_card_id") val physicalCardId: String,
    @SerialName("seller_confirmed_condition") val sellerConfirmedCondition: String? = null,
    @SerialName("suggested_condition") val suggestedCondition: String? = null,
)

/** Row shape for `public.physical_cards`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class PhysicalCardsRow(
    @SerialName("account_id") val accountId: String,
    @SerialName("acquisition_id") val acquisitionId: String? = null,
    @SerialName("allocation_channel") val allocationChannel: String? = null,
    @SerialName("allocation_ref_id") val allocationRefId: String? = null,
    val attributes: List<String>,
    @SerialName("batch_position") val batchPosition: Int? = null,
    @SerialName("card_number") val cardNumber: String? = null,
    @SerialName("catalogue_card_id") val catalogueCardId: String? = null,
    @SerialName("cert_number") val certNumber: String? = null,
    @SerialName("cert_verified") val certVerified: Boolean,
    @SerialName("cm_trend_eur") val cmTrendEur: Double? = null,
    @SerialName("collection_type") val collectionType: String,
    val condition: String? = null,
    @SerialName("condition_source") val conditionSource: String? = null,
    @SerialName("created_at") val createdAt: String,
    @SerialName("decided_route") val decidedRoute: String? = null,
    @SerialName("ebay_listing_id") val ebayListingId: String? = null,
    @SerialName("ebay_offer_id") val ebayOfferId: String? = null,
    @SerialName("ebay_price_avg") val ebayPriceAvg: Double? = null,
    @SerialName("ebay_price_low") val ebayPriceLow: Double? = null,
    @SerialName("ebay_price_top") val ebayPriceTop: Double? = null,
    @SerialName("fx_rate_eur_gbp") val fxRateEurGbp: Double? = null,
    @SerialName("fx_rate_usd_gbp") val fxRateUsdGbp: Double? = null,
    val game: String,
    val grade: String? = null,
    @SerialName("grading_company") val gradingCompany: String? = null,
    val id: String,
    @SerialName("id_verified_by_seller") val idVerifiedBySeller: Boolean,
    @SerialName("is_graded") val isGraded: Boolean,
    @SerialName("is_promo") val isPromo: Boolean,
    val language: String,
    @SerialName("legacy_card_id") val legacyCardId: String? = null,
    @SerialName("listing_description") val listingDescription: String? = null,
    @SerialName("listing_title") val listingTitle: String? = null,
    val name: String? = null,
    @SerialName("name_confidence") val nameConfidence: Double? = null,
    val notes: String? = null,
    @SerialName("photo_thumb_urls") val photoThumbUrls: List<String>,
    @SerialName("photo_urls") val photoUrls: List<String>,
    @SerialName("purchase_cost") val purchaseCost: Double? = null,
    val rarity: String? = null,
    @SerialName("sale_fees") val saleFees: Double? = null,
    @SerialName("sale_platform") val salePlatform: String? = null,
    @SerialName("sale_price") val salePrice: Double? = null,
    @SerialName("scan_batch_id") val scanBatchId: String? = null,
    @SerialName("set_confidence") val setConfidence: Double? = null,
    @SerialName("set_name") val setName: String? = null,
    val sku: String? = null,
    @SerialName("sold_at") val soldAt: String? = null,
    val status: String,
    @SerialName("storage_location") val storageLocation: String? = null,
    @SerialName("suggested_price") val suggestedPrice: Double? = null,
    @SerialName("tcg_id") val tcgId: String? = null,
    @SerialName("tcp_market_usd") val tcpMarketUsd: Double? = null,
)

/** Row shape for `public.profiles`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class ProfilesRow(
    @SerialName("aged_inventory_days") val agedInventoryDays: Int,
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("dispatch_address_city") val dispatchAddressCity: String? = null,
    @SerialName("dispatch_address_country") val dispatchAddressCountry: String,
    @SerialName("dispatch_address_line1") val dispatchAddressLine1: String? = null,
    @SerialName("dispatch_address_postcode") val dispatchAddressPostcode: String? = null,
    val id: String,
    @SerialName("is_admin") val isAdmin: Boolean,
    @SerialName("pricing_ebay_fee_fixed") val pricingEbayFeeFixed: Double? = null,
    @SerialName("pricing_ebay_fee_rate") val pricingEbayFeeRate: Double? = null,
    @SerialName("pricing_min_profit_pct") val pricingMinProfitPct: Double,
    @SerialName("pricing_min_sale_value") val pricingMinSaleValue: Double,
    @SerialName("pricing_packaging_cost") val pricingPackagingCost: Double,
    @SerialName("pricing_postage_cost") val pricingPostageCost: Double,
    @SerialName("pricing_shipping_cost") val pricingShippingCost: Double,
    @SerialName("pricing_tax_rate") val pricingTaxRate: Double,
    @SerialName("seller_type") val sellerType: String,
    @SerialName("seller_type_source") val sellerTypeSource: String,
)

/** Row shape for `public.scan_items`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class ScanItemsRow(
    @SerialName("batch_id") val batchId: String,
    @SerialName("created_at") val createdAt: String,
    val id: String,
    @SerialName("physical_card_id") val physicalCardId: String? = null,
    @SerialName("public_url") val publicUrl: String? = null,
    val side: String? = null,
    @SerialName("sort_order") val sortOrder: Int,
    val status: String,
    @SerialName("storage_path") val storagePath: String,
)

/** Row shape for `public.valuation_snapshots`. Generated from database.types.ts — do not edit by hand. */
@Serializable
public data class ValuationSnapshotsRow(
    @SerialName("cm_trend_eur") val cmTrendEur: Double? = null,
    val confidence: String? = null,
    @SerialName("created_at") val createdAt: String,
    @SerialName("ebay_avg_gbp") val ebayAvgGbp: Double? = null,
    @SerialName("ebay_low_gbp") val ebayLowGbp: Double? = null,
    @SerialName("ebay_sale_count") val ebaySaleCount: Int? = null,
    @SerialName("ebay_source") val ebaySource: String? = null,
    @SerialName("ebay_top_gbp") val ebayTopGbp: Double? = null,
    @SerialName("fx_date") val fxDate: String? = null,
    @SerialName("fx_eur_gbp") val fxEurGbp: Double? = null,
    @SerialName("fx_usd_gbp") val fxUsdGbp: Double? = null,
    val id: String,
    @SerialName("is_current") val isCurrent: Boolean,
    @SerialName("physical_card_id") val physicalCardId: String,
    @SerialName("snapshot_version") val snapshotVersion: Int,
    @SerialName("suggested_price_gbp") val suggestedPriceGbp: Double? = null,
    @SerialName("tcp_market_usd") val tcpMarketUsd: Double? = null,
)
