// AUTO-GENERATED by scripts/gen-swift-api.ts from src/api/*.ts (Zod schemas) — do not edit by
// hand. Regenerate via `npm run build`. See README.md "Releasing a new version".

import Foundation

public struct ApiError: Codable, Sendable {
    public let error: String

    public init(error: String) {
        self.error = error
    }
}

public struct IdentifyRequest: Codable, Sendable {
    public let imageUrls: [String]?
    public let inlineImages: [String]?
    public let taxonomyAspects: [TaxonomyAspect]?
    public let imageHash: String?
    public let game: String?
    public let games: [String]?

    public init(imageUrls: [String]?, inlineImages: [String]?, taxonomyAspects: [TaxonomyAspect]?, imageHash: String?, game: String?, games: [String]?) {
        self.imageUrls = imageUrls
        self.inlineImages = inlineImages
        self.taxonomyAspects = taxonomyAspects
        self.imageHash = imageHash
        self.game = game
        self.games = games
    }
}

public struct TaxonomyAspect: Codable, Sendable {
    public let localizedAspectName: String
    public let aspectConstraint: AspectConstraint?
    public let aspectValues: [AspectValue]?

    public init(localizedAspectName: String, aspectConstraint: AspectConstraint?, aspectValues: [AspectValue]?) {
        self.localizedAspectName = localizedAspectName
        self.aspectConstraint = aspectConstraint
        self.aspectValues = aspectValues
    }
}

public struct AspectConstraint: Codable, Sendable {
    public let aspectMode: String?

    public init(aspectMode: String?) {
        self.aspectMode = aspectMode
    }
}

public struct AspectValue: Codable, Sendable {
    public let localizedValue: String

    public init(localizedValue: String) {
        self.localizedValue = localizedValue
    }
}

public struct IdentifyResponse: Codable, Sendable {
    public let game: String
    public let gameConfidence: GameConfidence
    public let gameLowConfidence: Bool
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let cardType: String?
    public let estimatedGrade: String
    public let confidence: GameConfidence
    public let attributes: [String]
    public let isPromo: Bool
    public let language: String
    public let rarity: String?
    public let imageRoles: ImageRoles
    public let flaws: [Flaw]
    public let fieldSources: [String: FieldSources]?
    public let apiUsage: ApiUsage?
    public let cached: Bool?

    enum CodingKeys: String, CodingKey {
        case game
        case gameConfidence = "game_confidence"
        case gameLowConfidence = "game_low_confidence"
        case name
        case setName = "set_name"
        case cardNumber = "card_number"
        case cardType = "card_type"
        case estimatedGrade = "estimated_grade"
        case confidence
        case attributes
        case isPromo = "is_promo"
        case language
        case rarity
        case imageRoles = "image_roles"
        case flaws
        case fieldSources = "field_sources"
        case apiUsage = "_api_usage"
        case cached
    }

    public init(game: String, gameConfidence: GameConfidence, gameLowConfidence: Bool, name: String, setName: String?, cardNumber: String?, cardType: String?, estimatedGrade: String, confidence: GameConfidence, attributes: [String], isPromo: Bool, language: String, rarity: String?, imageRoles: ImageRoles, flaws: [Flaw], fieldSources: [String: FieldSources]?, apiUsage: ApiUsage?, cached: Bool?) {
        self.game = game
        self.gameConfidence = gameConfidence
        self.gameLowConfidence = gameLowConfidence
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.cardType = cardType
        self.estimatedGrade = estimatedGrade
        self.confidence = confidence
        self.attributes = attributes
        self.isPromo = isPromo
        self.language = language
        self.rarity = rarity
        self.imageRoles = imageRoles
        self.flaws = flaws
        self.fieldSources = fieldSources
        self.apiUsage = apiUsage
        self.cached = cached
    }
}

public enum GameConfidence: String, Codable, Sendable {
    case high = "high"
    case medium = "medium"
    case low = "low"
}

public struct ImageRoles: Codable, Sendable {
    public let front: Int
    public let back: Int?
    public let details: [Int]

    public init(front: Int, back: Int?, details: [Int]) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Flaw: Codable, Sendable {
    public let description: String
    public let region: String
    public let side: Side
    public let x: Double
    public let y: Double
    public let w: Double
    public let h: Double
    public let severity: Severity

    public init(description: String, region: String, side: Side, x: Double, y: Double, w: Double, h: Double, severity: Severity) {
        self.description = description
        self.region = region
        self.side = side
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        self.severity = severity
    }
}

public enum Side: String, Codable, Sendable {
    case front = "front"
    case back = "back"
    case unknown = "unknown"
}

public enum Severity: String, Codable, Sendable {
    case minor = "minor"
    case moderate = "moderate"
    case major = "major"
}

public struct FieldSources: Codable, Sendable {
    public let source: Source
    public let confidence: String?

    public init(source: Source, confidence: String?) {
        self.source = source
        self.confidence = confidence
    }
}

public enum Source: String, Codable, Sendable {
    case vision = "vision"
    case seller = "seller"
}

public struct ApiUsage: Codable, Sendable {
    public let model: Model
    public let escalated: Bool
    public let inputTokens: Int
    public let outputTokens: Int
    public let estimatedCostUsd: Double
    public let cached: Bool

    enum CodingKeys: String, CodingKey {
        case model
        case escalated
        case inputTokens = "input_tokens"
        case outputTokens = "output_tokens"
        case estimatedCostUsd = "estimated_cost_usd"
        case cached
    }

    public init(model: Model, escalated: Bool, inputTokens: Int, outputTokens: Int, estimatedCostUsd: Double, cached: Bool) {
        self.model = model
        self.escalated = escalated
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
        self.estimatedCostUsd = estimatedCostUsd
        self.cached = cached
    }
}

public enum Model: String, Codable, Sendable {
    case gpt4o = "gpt-4o"
    case gpt4oMini = "gpt-4o-mini"
}

public struct CaptureCommitRequest: Codable, Sendable {
    public let imageUrls: ImageUrls?
    public let inlineImages: InlineImages?
    public let resolvedMatch: ResolvedMatch?
    public let ocr: Ocr?
    public let purchaseCost: Double?
    public let collectionType: CollectionType?

    public init(imageUrls: ImageUrls?, inlineImages: InlineImages?, resolvedMatch: ResolvedMatch?, ocr: Ocr?, purchaseCost: Double?, collectionType: CollectionType?) {
        self.imageUrls = imageUrls
        self.inlineImages = inlineImages
        self.resolvedMatch = resolvedMatch
        self.ocr = ocr
        self.purchaseCost = purchaseCost
        self.collectionType = collectionType
    }
}

public struct ImageUrls: Codable, Sendable {
    public let front: String
    public let back: String
    public let details: [Detail]?

    public init(front: String, back: String, details: [Detail]?) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Detail: Codable, Sendable {
    public let side: Side2?
    public let corner: String?
    public let region: String?
    public let url: String

    public init(side: Side2?, corner: String?, region: String?, url: String) {
        self.side = side
        self.corner = corner
        self.region = region
        self.url = url
    }
}

public enum Side2: String, Codable, Sendable {
    case front = "front"
    case back = "back"
}

public struct InlineImages: Codable, Sendable {
    public let front: String
    public let back: String
    public let details: [Detail2]?

    public init(front: String, back: String, details: [Detail2]?) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Detail2: Codable, Sendable {
    public let side: Side3?
    public let corner: String?
    public let dataUrl: String

    public init(side: Side3?, corner: String?, dataUrl: String) {
        self.side = side
        self.corner = corner
        self.dataUrl = dataUrl
    }
}

public enum Side3: String, Codable, Sendable {
    case front = "front"
    case back = "back"
}

public struct ResolvedMatch: Codable, Sendable {
    public let nativeId: String
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let rarity: String?
    public let language: String

    public init(nativeId: String, name: String, setName: String?, cardNumber: String?, rarity: String?, language: String) {
        self.nativeId = nativeId
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.rarity = rarity
        self.language = language
    }
}

public struct Ocr: Codable, Sendable {
    public let name: String?
    public let number: String?

    public init(name: String?, number: String?) {
        self.name = name
        self.number = number
    }
}

public enum CollectionType: String, Codable, Sendable {
    case personal = "personal"
    case resale = "resale"
}

public struct CaptureCommitResponse: Codable, Sendable {
    public let physicalCardId: String
    public let legacyCardId: String?
    public let game: String
    public let gameDisplayName: String
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let condition: String?
    public let rarity: String?
    public let suggestedPrice: Double?
    public let ebay: Ebay?
    public let subGrades: [String: JSONValue]?

    public init(physicalCardId: String, legacyCardId: String?, game: String, gameDisplayName: String, name: String, setName: String?, cardNumber: String?, condition: String?, rarity: String?, suggestedPrice: Double?, ebay: Ebay?, subGrades: [String: JSONValue]?) {
        self.physicalCardId = physicalCardId
        self.legacyCardId = legacyCardId
        self.game = game
        self.gameDisplayName = gameDisplayName
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.condition = condition
        self.rarity = rarity
        self.suggestedPrice = suggestedPrice
        self.ebay = ebay
        self.subGrades = subGrades
    }
}

public struct Ebay: Codable, Sendable {
    public let low: Double?
    public let avg: Double?
    public let top: Double?

    public init(low: Double?, avg: Double?, top: Double?) {
        self.low = low
        self.avg = avg
        self.top = top
    }
}

public struct RecommendRequest: Codable, Sendable {
    public let physicalCardId: String
    public let isVintage: Bool?

    public init(physicalCardId: String, isVintage: Bool?) {
        self.physicalCardId = physicalCardId
        self.isVintage = isVintage
    }
}

public struct RecommendResponse: Codable, Sendable {
    public let route: RecommendedRoute
    public let alternatives: [Alternative]
    public let economics: Economics
    public let assumptions: [String]
    public let explanation: String
    public let confidence: GameConfidence
    public let calculationVersion: String
    public let physicalCardId: String
    public let currentRoute: RecommendedRoute?
    public let priceSource: String?
    public let priceConfidence: GameConfidence?
    public let currencyNote: String?
    public let gradeEV: Double?
    public let psa10PriceGbp: Double?
    public let p10: Double?
    public let p9: Double?
    public let gradingCostGbp: Double?
    public let rawNetGbp: Double?
    public let gradeEVConfidence: GradeEVConfidence?

    enum CodingKeys: String, CodingKey {
        case route
        case alternatives
        case economics
        case assumptions
        case explanation
        case confidence
        case calculationVersion = "calculation_version"
        case physicalCardId
        case currentRoute
        case priceSource
        case priceConfidence
        case currencyNote
        case gradeEV
        case psa10PriceGbp
        case p10
        case p9
        case gradingCostGbp
        case rawNetGbp
        case gradeEVConfidence
    }

    public init(route: RecommendedRoute, alternatives: [Alternative], economics: Economics, assumptions: [String], explanation: String, confidence: GameConfidence, calculationVersion: String, physicalCardId: String, currentRoute: RecommendedRoute?, priceSource: String?, priceConfidence: GameConfidence?, currencyNote: String?, gradeEV: Double?, psa10PriceGbp: Double?, p10: Double?, p9: Double?, gradingCostGbp: Double?, rawNetGbp: Double?, gradeEVConfidence: GradeEVConfidence?) {
        self.route = route
        self.alternatives = alternatives
        self.economics = economics
        self.assumptions = assumptions
        self.explanation = explanation
        self.confidence = confidence
        self.calculationVersion = calculationVersion
        self.physicalCardId = physicalCardId
        self.currentRoute = currentRoute
        self.priceSource = priceSource
        self.priceConfidence = priceConfidence
        self.currencyNote = currencyNote
        self.gradeEV = gradeEV
        self.psa10PriceGbp = psa10PriceGbp
        self.p10 = p10
        self.p9 = p9
        self.gradingCostGbp = gradingCostGbp
        self.rawNetGbp = rawNetGbp
        self.gradeEVConfidence = gradeEVConfidence
    }
}

public enum RecommendedRoute: String, Codable, Sendable {
    case listSingle = "list_single"
    case bundle = "bundle"
    case bulk = "bulk"
    case hold = "hold"
    case gradeReview = "grade_review"
    case restorationReview = "restoration_review"
    case doNotList = "do_not_list"
}

public struct Alternative: Codable, Sendable {
    public let route: RecommendedRoute
    public let expectedNetGbp: Double?
    public let why: String

    enum CodingKeys: String, CodingKey {
        case route
        case expectedNetGbp = "expected_net_gbp"
        case why
    }

    public init(route: RecommendedRoute, expectedNetGbp: Double?, why: String) {
        self.route = route
        self.expectedNetGbp = expectedNetGbp
        self.why = why
    }
}

public struct Economics: Codable, Sendable {
    public let expectedSaleGbp: Double?
    public let feesGbp: Double?
    public let postageGbp: Double?
    public let costBasisGbp: Double?
    public let expectedNetGbp: Double?
    public let liquidity: Liquidity?

    enum CodingKeys: String, CodingKey {
        case expectedSaleGbp = "expected_sale_gbp"
        case feesGbp = "fees_gbp"
        case postageGbp = "postage_gbp"
        case costBasisGbp = "cost_basis_gbp"
        case expectedNetGbp = "expected_net_gbp"
        case liquidity
    }

    public init(expectedSaleGbp: Double?, feesGbp: Double?, postageGbp: Double?, costBasisGbp: Double?, expectedNetGbp: Double?, liquidity: Liquidity?) {
        self.expectedSaleGbp = expectedSaleGbp
        self.feesGbp = feesGbp
        self.postageGbp = postageGbp
        self.costBasisGbp = costBasisGbp
        self.expectedNetGbp = expectedNetGbp
        self.liquidity = liquidity
    }
}

public enum Liquidity: String, Codable, Sendable {
    case high = "high"
    case medium = "medium"
    case low = "low"
}

public enum GradeEVConfidence: String, Codable, Sendable {
    case medium = "medium"
    case low = "low"
}

public struct RecommendBatchRequest: Codable, Sendable {
    public let cards: [RecommendBatchCardInput]

    public init(cards: [RecommendBatchCardInput]) {
        self.cards = cards
    }
}

public struct RecommendBatchCardInput: Codable, Sendable {
    public let id: String
    public let avgGbp: Double?
    public let lowGbp: Double?
    public let topGbp: Double?
    public let priceSource: String?
    public let saleCount: Int?
    public let approxSaleCount: Bool?
    public let condition: String?
    public let costBasis: Double?
    public let collectionType: CollectionType2?
    public let isVintage: Bool?

    public init(id: String, avgGbp: Double?, lowGbp: Double?, topGbp: Double?, priceSource: String?, saleCount: Int?, approxSaleCount: Bool?, condition: String?, costBasis: Double?, collectionType: CollectionType2?, isVintage: Bool?) {
        self.id = id
        self.avgGbp = avgGbp
        self.lowGbp = lowGbp
        self.topGbp = topGbp
        self.priceSource = priceSource
        self.saleCount = saleCount
        self.approxSaleCount = approxSaleCount
        self.condition = condition
        self.costBasis = costBasis
        self.collectionType = collectionType
        self.isVintage = isVintage
    }
}

public enum CollectionType2: String, Codable, Sendable {
    case personal = "personal"
    case resale = "resale"
}

public struct RecommendBatchResponse: Codable, Sendable {
    public let results: [RecommendBatchResult]

    public init(results: [RecommendBatchResult]) {
        self.results = results
    }
}

public struct RecommendBatchResult: Codable, Sendable {
    public let id: String
    public let route: RecommendedRoute?
    public let alternatives: [Alternative]
    public let economics: Economics?
    public let assumptions: [String]
    public let explanation: String?
    public let confidence: GameConfidence?
    public let calculationVersion: String?
    public let priceSource: String?
    public let priceConfidence: GameConfidence?
    public let currencyNote: String?

    enum CodingKeys: String, CodingKey {
        case id
        case route
        case alternatives
        case economics
        case assumptions
        case explanation
        case confidence
        case calculationVersion = "calculation_version"
        case priceSource
        case priceConfidence
        case currencyNote
    }

    public init(id: String, route: RecommendedRoute?, alternatives: [Alternative], economics: Economics?, assumptions: [String], explanation: String?, confidence: GameConfidence?, calculationVersion: String?, priceSource: String?, priceConfidence: GameConfidence?, currencyNote: String?) {
        self.id = id
        self.route = route
        self.alternatives = alternatives
        self.economics = economics
        self.assumptions = assumptions
        self.explanation = explanation
        self.confidence = confidence
        self.calculationVersion = calculationVersion
        self.priceSource = priceSource
        self.priceConfidence = priceConfidence
        self.currencyNote = currencyNote
    }
}

public struct CardSearchRequest: Codable, Sendable {
    public let q: String
    public let game: String?

    public init(q: String, game: String?) {
        self.q = q
        self.game = game
    }
}

public struct CardSearchResponse: Codable, Sendable {
    public let results: [CardSearchResult]

    public init(results: [CardSearchResult]) {
        self.results = results
    }
}

public struct CardSearchResult: Codable, Sendable {
    public let tcgId: String
    public let name: String
    public let setName: String?
    public let number: String?
    public let rarity: String?
    public let image: String?
    public let marketGbp: Double?
    public let game: String?
    public let gameDisplayName: String?
    public let printingCount: Int?
    public let printings: [Printing]?

    public init(tcgId: String, name: String, setName: String?, number: String?, rarity: String?, image: String?, marketGbp: Double?, game: String?, gameDisplayName: String?, printingCount: Int?, printings: [Printing]?) {
        self.tcgId = tcgId
        self.name = name
        self.setName = setName
        self.number = number
        self.rarity = rarity
        self.image = image
        self.marketGbp = marketGbp
        self.game = game
        self.gameDisplayName = gameDisplayName
        self.printingCount = printingCount
        self.printings = printings
    }
}

public struct Printing: Codable, Sendable {
    public let tcgId: String
    public let setName: String?
    public let number: String?
    public let rarity: String?
    public let image: String?
    public let marketGbp: Double?

    public init(tcgId: String, setName: String?, number: String?, rarity: String?, image: String?, marketGbp: Double?) {
        self.tcgId = tcgId
        self.setName = setName
        self.number = number
        self.rarity = rarity
        self.image = image
        self.marketGbp = marketGbp
    }
}

public struct PriceRequest: Codable, Sendable {
    public let name: String
    public let setName: String
    public let cardNumber: String
    public let condition: String?
    public let tcgId: String?
    public let tcgBaseline: TcgBaseline?
    public let noCache: Bool?

    enum CodingKeys: String, CodingKey {
        case name
        case setName = "set_name"
        case cardNumber = "card_number"
        case condition
        case tcgId = "tcg_id"
        case tcgBaseline
        case noCache
    }

    public init(name: String, setName: String, cardNumber: String, condition: String?, tcgId: String?, tcgBaseline: TcgBaseline?, noCache: Bool?) {
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.condition = condition
        self.tcgId = tcgId
        self.tcgBaseline = tcgBaseline
        self.noCache = noCache
    }
}

public struct TcgBaseline: Codable, Sendable {
    public let tcpMarketUsd: Double?
    public let cmTrendEur: Double?

    enum CodingKeys: String, CodingKey {
        case tcpMarketUsd = "tcp_market_usd"
        case cmTrendEur = "cm_trend_eur"
    }

    public init(tcpMarketUsd: Double?, cmTrendEur: Double?) {
        self.tcpMarketUsd = tcpMarketUsd
        self.cmTrendEur = cmTrendEur
    }
}

public struct PriceResponse: Codable, Sendable {
    public let low: Double?
    public let avg: Double?
    public let top: Double?
    public let priceSource: String?
    public let provider: String?
    public let fxRate: Double?
    public let fxDate: String?
    public let saleCount: Int?
    public let approxSaleCount: Bool?
    public let comps: [[String: JSONValue]]?
    public let confidence: GameConfidence?
    public let priceWarning: String?
    public let cached: Bool?
    public let stale: Bool?
    public let fetchedAt: String?
    public let error: String?

    enum CodingKeys: String, CodingKey {
        case low
        case avg
        case top
        case priceSource = "price_source"
        case provider
        case fxRate = "fx_rate"
        case fxDate = "fx_date"
        case saleCount = "sale_count"
        case approxSaleCount = "approx_sale_count"
        case comps
        case confidence
        case priceWarning = "price_warning"
        case cached
        case stale
        case fetchedAt = "fetched_at"
        case error
    }

    public init(low: Double?, avg: Double?, top: Double?, priceSource: String?, provider: String?, fxRate: Double?, fxDate: String?, saleCount: Int?, approxSaleCount: Bool?, comps: [[String: JSONValue]]?, confidence: GameConfidence?, priceWarning: String?, cached: Bool?, stale: Bool?, fetchedAt: String?, error: String?) {
        self.low = low
        self.avg = avg
        self.top = top
        self.priceSource = priceSource
        self.provider = provider
        self.fxRate = fxRate
        self.fxDate = fxDate
        self.saleCount = saleCount
        self.approxSaleCount = approxSaleCount
        self.comps = comps
        self.confidence = confidence
        self.priceWarning = priceWarning
        self.cached = cached
        self.stale = stale
        self.fetchedAt = fetchedAt
        self.error = error
    }
}

public struct CertLookupRequest: Codable, Sendable {
    public let grader: Grader
    public let certNumber: String

    public init(grader: Grader, certNumber: String) {
        self.grader = grader
        self.certNumber = certNumber
    }
}

public enum Grader: String, Codable, Sendable {
    case pSA = "PSA"
}

public struct CertLookupResponse: Codable, Sendable {
    public let found: Bool
    public let grader: Grader2
    public let certNumber: String
    public let grade: String?
    public let gradeDescription: String?
    public let subject: String?
    public let year: String?
    public let brand: String?
    public let category: String?
    public let cardNumber: String?
    public let variety: String?
    public let labelType: String?

    public init(found: Bool, grader: Grader2, certNumber: String, grade: String?, gradeDescription: String?, subject: String?, year: String?, brand: String?, category: String?, cardNumber: String?, variety: String?, labelType: String?) {
        self.found = found
        self.grader = grader
        self.certNumber = certNumber
        self.grade = grade
        self.gradeDescription = gradeDescription
        self.subject = subject
        self.year = year
        self.brand = brand
        self.category = category
        self.cardNumber = cardNumber
        self.variety = variety
        self.labelType = labelType
    }
}

public enum Grader2: String, Codable, Sendable {
    case pSA = "PSA"
}

public struct ChannelListingRequest: Codable, Sendable {
    public let channel: Channel
    public let cardRef: String
    public let priceGbp: Double
    public let condition: String

    public init(channel: Channel, cardRef: String, priceGbp: Double, condition: String) {
        self.channel = channel
        self.cardRef = cardRef
        self.priceGbp = priceGbp
        self.condition = condition
    }
}

public enum Channel: String, Codable, Sendable {
    case cardtrader = "cardtrader"
}

public struct ChannelListingResponse: Codable, Sendable {
    public let channel: Channel
    public let channelListingId: String?
    public let url: String?
    public let status: Status
    public let error: String?

    public init(channel: Channel, channelListingId: String?, url: String?, status: Status, error: String?) {
        self.channel = channel
        self.channelListingId = channelListingId
        self.url = url
        self.status = status
        self.error = error
    }
}

public enum Status: String, Codable, Sendable {
    case listed = "listed"
    case failed = "failed"
}
