// AUTO-GENERATED by scripts/gen-swift-api.ts from src/api/*.ts (Zod schemas) — do not edit by
// hand. Regenerate via `npm run build`. See README.md "Releasing a new version".

import Foundation

public struct ApiError: Codable, Sendable {
    public let error: String

    public init(error: String) {
        self.error = error
    }
}

public struct IdentifyRequest: Codable, Sendable {
    public let imagePaths: [String]?
    public let imageUrls: [String]?
    public let inlineImages: [String]?
    public let taxonomyAspects: [TaxonomyAspect]?
    public let imageHash: String?
    public let game: String?
    public let games: [String]?
    public let ocrCardNumber: String?
    public let ocrSetCode: String?
    public let ocrSetName: String?
    public let ocrName: String?

    public init(imagePaths: [String]?, imageUrls: [String]?, inlineImages: [String]?, taxonomyAspects: [TaxonomyAspect]?, imageHash: String?, game: String?, games: [String]?, ocrCardNumber: String?, ocrSetCode: String?, ocrSetName: String?, ocrName: String?) {
        self.imagePaths = imagePaths
        self.imageUrls = imageUrls
        self.inlineImages = inlineImages
        self.taxonomyAspects = taxonomyAspects
        self.imageHash = imageHash
        self.game = game
        self.games = games
        self.ocrCardNumber = ocrCardNumber
        self.ocrSetCode = ocrSetCode
        self.ocrSetName = ocrSetName
        self.ocrName = ocrName
    }
}

public struct TaxonomyAspect: Codable, Sendable {
    public let localizedAspectName: String
    public let aspectConstraint: AspectConstraint?
    public let aspectValues: [AspectValue]?

    public init(localizedAspectName: String, aspectConstraint: AspectConstraint?, aspectValues: [AspectValue]?) {
        self.localizedAspectName = localizedAspectName
        self.aspectConstraint = aspectConstraint
        self.aspectValues = aspectValues
    }
}

public struct AspectConstraint: Codable, Sendable {
    public let aspectMode: String?

    public init(aspectMode: String?) {
        self.aspectMode = aspectMode
    }
}

public struct AspectValue: Codable, Sendable {
    public let localizedValue: String

    public init(localizedValue: String) {
        self.localizedValue = localizedValue
    }
}

public struct IdentifyResponse: Codable, Sendable {
    public let game: String
    public let gameConfidence: GameConfidence
    public let gameLowConfidence: Bool
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let cardType: String?
    public let estimatedGrade: String
    public let confidence: GameConfidence
    public let attributes: [String]
    public let isPromo: Bool
    public let language: String
    public let rarity: String?
    public let imageRoles: ImageRoles
    public let flaws: [Flaw]
    public let fieldSources: [String: FieldSources]?
    public let apiUsage: ApiUsage?
    public let cached: Bool?
    public let tier: Tier?
    public let aiCallAvoided: Bool?

    enum CodingKeys: String, CodingKey {
        case game
        case gameConfidence = "game_confidence"
        case gameLowConfidence = "game_low_confidence"
        case name
        case setName = "set_name"
        case cardNumber = "card_number"
        case cardType = "card_type"
        case estimatedGrade = "estimated_grade"
        case confidence
        case attributes
        case isPromo = "is_promo"
        case language
        case rarity
        case imageRoles = "image_roles"
        case flaws
        case fieldSources = "field_sources"
        case apiUsage = "_api_usage"
        case cached
        case tier
        case aiCallAvoided = "ai_call_avoided"
    }

    public init(game: String, gameConfidence: GameConfidence, gameLowConfidence: Bool, name: String, setName: String?, cardNumber: String?, cardType: String?, estimatedGrade: String, confidence: GameConfidence, attributes: [String], isPromo: Bool, language: String, rarity: String?, imageRoles: ImageRoles, flaws: [Flaw], fieldSources: [String: FieldSources]?, apiUsage: ApiUsage?, cached: Bool?, tier: Tier?, aiCallAvoided: Bool?) {
        self.game = game
        self.gameConfidence = gameConfidence
        self.gameLowConfidence = gameLowConfidence
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.cardType = cardType
        self.estimatedGrade = estimatedGrade
        self.confidence = confidence
        self.attributes = attributes
        self.isPromo = isPromo
        self.language = language
        self.rarity = rarity
        self.imageRoles = imageRoles
        self.flaws = flaws
        self.fieldSources = fieldSources
        self.apiUsage = apiUsage
        self.cached = cached
        self.tier = tier
        self.aiCallAvoided = aiCallAvoided
    }
}

public enum GameConfidence: String, Codable, Sendable {
    case high = "high"
    case medium = "medium"
    case low = "low"
}

public struct ImageRoles: Codable, Sendable {
    public let front: Int
    public let back: Int?
    public let details: [Int]

    public init(front: Int, back: Int?, details: [Int]) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Flaw: Codable, Sendable {
    public let description: String
    public let region: String
    public let side: Side
    public let x: Double
    public let y: Double
    public let w: Double
    public let h: Double
    public let severity: Severity

    public init(description: String, region: String, side: Side, x: Double, y: Double, w: Double, h: Double, severity: Severity) {
        self.description = description
        self.region = region
        self.side = side
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        self.severity = severity
    }
}

public enum Side: String, Codable, Sendable {
    case front = "front"
    case back = "back"
    case unknown = "unknown"
}

public enum Severity: String, Codable, Sendable {
    case minor = "minor"
    case moderate = "moderate"
    case major = "major"
}

public struct FieldSources: Codable, Sendable {
    public let source: Source
    public let confidence: String?

    public init(source: Source, confidence: String?) {
        self.source = source
        self.confidence = confidence
    }
}

public enum Source: String, Codable, Sendable {
    case vision = "vision"
    case seller = "seller"
}

public struct ApiUsage: Codable, Sendable {
    public let model: Model
    public let escalated: Bool
    public let inputTokens: Int
    public let outputTokens: Int
    public let estimatedCostUsd: Double
    public let cached: Bool

    enum CodingKeys: String, CodingKey {
        case model
        case escalated
        case inputTokens = "input_tokens"
        case outputTokens = "output_tokens"
        case estimatedCostUsd = "estimated_cost_usd"
        case cached
    }

    public init(model: Model, escalated: Bool, inputTokens: Int, outputTokens: Int, estimatedCostUsd: Double, cached: Bool) {
        self.model = model
        self.escalated = escalated
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
        self.estimatedCostUsd = estimatedCostUsd
        self.cached = cached
    }
}

public enum Model: String, Codable, Sendable {
    case gpt4o = "gpt-4o"
    case gpt4oMini = "gpt-4o-mini"
}

public enum Tier: String, Codable, Sendable {
    case tier0 = "tier0"
    case vision = "vision"
}

public struct IdentifyAmbiguousResponse: Codable, Sendable {
    public let tier: IdentifyAmbiguousTier
    public let candidates: [IdentifyCandidate]

    public init(tier: IdentifyAmbiguousTier, candidates: [IdentifyCandidate]) {
        self.tier = tier
        self.candidates = candidates
    }
}

public enum IdentifyAmbiguousTier: String, Codable, Sendable {
    case ambiguous = "ambiguous"
}

public struct IdentifyCandidate: Codable, Sendable {
    public let game: String
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let nativeId: String

    public init(game: String, name: String, setName: String?, cardNumber: String?, nativeId: String) {
        self.game = game
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.nativeId = nativeId
    }
}

public struct CaptureCommitRequest: Codable, Sendable {
    public let imagePaths: ImagePaths?
    public let imageUrls: ImageUrls?
    public let inlineImages: InlineImages?
    public let resolvedMatch: CatalogueLookupMatch?
    public let game: Game?
    public let ocr: Ocr?
    public let purchaseCost: Double?
    public let collectionType: CollectionType?
    public let shotQuality: [ShotQualityDescriptor]?

    public init(imagePaths: ImagePaths?, imageUrls: ImageUrls?, inlineImages: InlineImages?, resolvedMatch: CatalogueLookupMatch?, game: Game?, ocr: Ocr?, purchaseCost: Double?, collectionType: CollectionType?, shotQuality: [ShotQualityDescriptor]?) {
        self.imagePaths = imagePaths
        self.imageUrls = imageUrls
        self.inlineImages = inlineImages
        self.resolvedMatch = resolvedMatch
        self.game = game
        self.ocr = ocr
        self.purchaseCost = purchaseCost
        self.collectionType = collectionType
        self.shotQuality = shotQuality
    }
}

public struct ImagePaths: Codable, Sendable {
    public let front: String
    public let back: String
    public let details: [Detail]?

    public init(front: String, back: String, details: [Detail]?) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Detail: Codable, Sendable {
    public let side: Side2?
    public let corner: String?
    public let region: String?
    public let path: String

    public init(side: Side2?, corner: String?, region: String?, path: String) {
        self.side = side
        self.corner = corner
        self.region = region
        self.path = path
    }
}

public enum Side2: String, Codable, Sendable {
    case front = "front"
    case back = "back"
}

public struct ImageUrls: Codable, Sendable {
    public let front: String
    public let back: String
    public let details: [Detail2]?

    public init(front: String, back: String, details: [Detail2]?) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Detail2: Codable, Sendable {
    public let side: Side3?
    public let corner: String?
    public let region: String?
    public let url: String

    public init(side: Side3?, corner: String?, region: String?, url: String) {
        self.side = side
        self.corner = corner
        self.region = region
        self.url = url
    }
}

public enum Side3: String, Codable, Sendable {
    case front = "front"
    case back = "back"
}

public struct InlineImages: Codable, Sendable {
    public let front: String
    public let back: String
    public let details: [Detail3]?

    public init(front: String, back: String, details: [Detail3]?) {
        self.front = front
        self.back = back
        self.details = details
    }
}

public struct Detail3: Codable, Sendable {
    public let side: Side4?
    public let corner: String?
    public let dataUrl: String

    public init(side: Side4?, corner: String?, dataUrl: String) {
        self.side = side
        self.corner = corner
        self.dataUrl = dataUrl
    }
}

public enum Side4: String, Codable, Sendable {
    case front = "front"
    case back = "back"
}

public struct CatalogueLookupMatch: Codable, Sendable {
    public let game: Game?
    public let nativeId: String
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let rarity: String?
    public let language: String
    public let image: String?

    public init(game: Game?, nativeId: String, name: String, setName: String?, cardNumber: String?, rarity: String?, language: String, image: String?) {
        self.game = game
        self.nativeId = nativeId
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.rarity = rarity
        self.language = language
        self.image = image
    }
}

public enum Game: String, Codable, Sendable {
    case pokemon = "pokemon"
    case pokemonJp = "pokemon-jp"
    case mtg = "mtg"
    case yugioh = "yugioh"
    case lorcana = "lorcana"
    case onePiece = "one-piece"
    case digimon = "digimon"
    case dbsFusion = "dbs-fusion"
}

public struct Ocr: Codable, Sendable {
    public let name: String?
    public let number: String?

    public init(name: String?, number: String?) {
        self.name = name
        self.number = number
    }
}

public enum CollectionType: String, Codable, Sendable {
    case personal = "personal"
    case resale = "resale"
}

public struct ShotQualityDescriptor: Codable, Sendable {
    public let side: Side5?
    public let corner: String?
    public let region: String?
    public let sharpness: Double?
    public let glare: Bool?
    public let cropped: Bool?
    public let skewDegrees: Double?
    public let orientation: Orientation?
    public let exposure: Exposure?
    public let centeringLR: Double?
    public let centeringTB: Double?

    public init(side: Side5?, corner: String?, region: String?, sharpness: Double?, glare: Bool?, cropped: Bool?, skewDegrees: Double?, orientation: Orientation?, exposure: Exposure?, centeringLR: Double?, centeringTB: Double?) {
        self.side = side
        self.corner = corner
        self.region = region
        self.sharpness = sharpness
        self.glare = glare
        self.cropped = cropped
        self.skewDegrees = skewDegrees
        self.orientation = orientation
        self.exposure = exposure
        self.centeringLR = centeringLR
        self.centeringTB = centeringTB
    }
}

public enum Side5: String, Codable, Sendable {
    case front = "front"
    case back = "back"
}

public enum Orientation: String, Codable, Sendable {
    case correct = "correct"
    case rotated90 = "rotated_90"
    case rotated180 = "rotated_180"
    case rotated270 = "rotated_270"
    case unknown = "unknown"
}

public enum Exposure: String, Codable, Sendable {
    case under = "under"
    case over = "over"
    case ok = "ok"
    case unknown = "unknown"
}

public struct CaptureCommitResponse: Codable, Sendable {
    public let physicalCardId: String
    public let legacyCardId: String?
    public let game: String
    public let gameDisplayName: String
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let condition: String?
    public let rarity: String?
    public let suggestedPrice: Double?
    public let ebay: Ebay?
    public let subGrades: [String: JSONValue]?
    public let image: String?

    public init(physicalCardId: String, legacyCardId: String?, game: String, gameDisplayName: String, name: String, setName: String?, cardNumber: String?, condition: String?, rarity: String?, suggestedPrice: Double?, ebay: Ebay?, subGrades: [String: JSONValue]?, image: String?) {
        self.physicalCardId = physicalCardId
        self.legacyCardId = legacyCardId
        self.game = game
        self.gameDisplayName = gameDisplayName
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.condition = condition
        self.rarity = rarity
        self.suggestedPrice = suggestedPrice
        self.ebay = ebay
        self.subGrades = subGrades
        self.image = image
    }
}

public struct Ebay: Codable, Sendable {
    public let low: Double?
    public let avg: Double?
    public let top: Double?

    public init(low: Double?, avg: Double?, top: Double?) {
        self.low = low
        self.avg = avg
        self.top = top
    }
}

public struct RecommendRequest: Codable, Sendable {
    public let physicalCardId: String
    public let isVintage: Bool?
    public let pricingSettings: PricingSettings?

    public init(physicalCardId: String, isVintage: Bool?, pricingSettings: PricingSettings?) {
        self.physicalCardId = physicalCardId
        self.isVintage = isVintage
        self.pricingSettings = pricingSettings
    }
}

public struct PricingSettings: Codable, Sendable {
    public let ebayFeeRate: Double
    public let ebayFeeFixed: Double
    public let packagingCost: Double
    public let shippingCost: Double
    public let taxRate: Double
    public let minProfitPct: Double
    public let minSaleValue: Double
    public let postageCost: Double

    public init(ebayFeeRate: Double, ebayFeeFixed: Double, packagingCost: Double, shippingCost: Double, taxRate: Double, minProfitPct: Double, minSaleValue: Double, postageCost: Double) {
        self.ebayFeeRate = ebayFeeRate
        self.ebayFeeFixed = ebayFeeFixed
        self.packagingCost = packagingCost
        self.shippingCost = shippingCost
        self.taxRate = taxRate
        self.minProfitPct = minProfitPct
        self.minSaleValue = minSaleValue
        self.postageCost = postageCost
    }
}

public struct RecommendResponse: Codable, Sendable {
    public let route: RecommendedRoute
    public let alternatives: [Alternative]
    public let economics: Economics
    public let assumptions: [String]
    public let explanation: String
    public let confidence: GameConfidence
    public let calculationVersion: String
    public let physicalCardId: String
    public let currentRoute: RecommendedRoute?
    public let priceSource: String?
    public let priceConfidence: GameConfidence?
    public let currencyNote: String?
    public let gradeEV: Double?
    public let psa10PriceGbp: Double?
    public let p10: Double?
    public let p9: Double?
    public let gradingCostGbp: Double?
    public let rawNetGbp: Double?
    public let gradeEVConfidence: GradeEVConfidence?

    enum CodingKeys: String, CodingKey {
        case route
        case alternatives
        case economics
        case assumptions
        case explanation
        case confidence
        case calculationVersion = "calculation_version"
        case physicalCardId
        case currentRoute
        case priceSource
        case priceConfidence
        case currencyNote
        case gradeEV
        case psa10PriceGbp
        case p10
        case p9
        case gradingCostGbp
        case rawNetGbp
        case gradeEVConfidence
    }

    public init(route: RecommendedRoute, alternatives: [Alternative], economics: Economics, assumptions: [String], explanation: String, confidence: GameConfidence, calculationVersion: String, physicalCardId: String, currentRoute: RecommendedRoute?, priceSource: String?, priceConfidence: GameConfidence?, currencyNote: String?, gradeEV: Double?, psa10PriceGbp: Double?, p10: Double?, p9: Double?, gradingCostGbp: Double?, rawNetGbp: Double?, gradeEVConfidence: GradeEVConfidence?) {
        self.route = route
        self.alternatives = alternatives
        self.economics = economics
        self.assumptions = assumptions
        self.explanation = explanation
        self.confidence = confidence
        self.calculationVersion = calculationVersion
        self.physicalCardId = physicalCardId
        self.currentRoute = currentRoute
        self.priceSource = priceSource
        self.priceConfidence = priceConfidence
        self.currencyNote = currencyNote
        self.gradeEV = gradeEV
        self.psa10PriceGbp = psa10PriceGbp
        self.p10 = p10
        self.p9 = p9
        self.gradingCostGbp = gradingCostGbp
        self.rawNetGbp = rawNetGbp
        self.gradeEVConfidence = gradeEVConfidence
    }
}

public enum RecommendedRoute: String, Codable, Sendable {
    case listSingle = "list_single"
    case bundle = "bundle"
    case bulk = "bulk"
    case hold = "hold"
    case gradeReview = "grade_review"
    case restorationReview = "restoration_review"
    case doNotList = "do_not_list"
}

public struct Alternative: Codable, Sendable {
    public let route: RecommendedRoute
    public let expectedNetGbp: Double?
    public let why: String

    enum CodingKeys: String, CodingKey {
        case route
        case expectedNetGbp = "expected_net_gbp"
        case why
    }

    public init(route: RecommendedRoute, expectedNetGbp: Double?, why: String) {
        self.route = route
        self.expectedNetGbp = expectedNetGbp
        self.why = why
    }
}

public struct Economics: Codable, Sendable {
    public let expectedSaleGbp: Double?
    public let feesGbp: Double?
    public let postageGbp: Double?
    public let costBasisGbp: Double?
    public let expectedNetGbp: Double?
    public let liquidity: Liquidity?

    enum CodingKeys: String, CodingKey {
        case expectedSaleGbp = "expected_sale_gbp"
        case feesGbp = "fees_gbp"
        case postageGbp = "postage_gbp"
        case costBasisGbp = "cost_basis_gbp"
        case expectedNetGbp = "expected_net_gbp"
        case liquidity
    }

    public init(expectedSaleGbp: Double?, feesGbp: Double?, postageGbp: Double?, costBasisGbp: Double?, expectedNetGbp: Double?, liquidity: Liquidity?) {
        self.expectedSaleGbp = expectedSaleGbp
        self.feesGbp = feesGbp
        self.postageGbp = postageGbp
        self.costBasisGbp = costBasisGbp
        self.expectedNetGbp = expectedNetGbp
        self.liquidity = liquidity
    }
}

public enum Liquidity: String, Codable, Sendable {
    case high = "high"
    case medium = "medium"
    case low = "low"
}

public enum GradeEVConfidence: String, Codable, Sendable {
    case medium = "medium"
    case low = "low"
}

public struct RecommendBatchRequest: Codable, Sendable {
    public let cards: [RecommendBatchCardInput]
    public let pricingSettings: PricingSettings?

    public init(cards: [RecommendBatchCardInput], pricingSettings: PricingSettings?) {
        self.cards = cards
        self.pricingSettings = pricingSettings
    }
}

public struct RecommendBatchCardInput: Codable, Sendable {
    public let id: String
    public let avgGbp: Double?
    public let lowGbp: Double?
    public let topGbp: Double?
    public let priceSource: String?
    public let saleCount: Int?
    public let approxSaleCount: Bool?
    public let condition: String?
    public let costBasis: Double?
    public let collectionType: CollectionType2?
    public let isVintage: Bool?

    public init(id: String, avgGbp: Double?, lowGbp: Double?, topGbp: Double?, priceSource: String?, saleCount: Int?, approxSaleCount: Bool?, condition: String?, costBasis: Double?, collectionType: CollectionType2?, isVintage: Bool?) {
        self.id = id
        self.avgGbp = avgGbp
        self.lowGbp = lowGbp
        self.topGbp = topGbp
        self.priceSource = priceSource
        self.saleCount = saleCount
        self.approxSaleCount = approxSaleCount
        self.condition = condition
        self.costBasis = costBasis
        self.collectionType = collectionType
        self.isVintage = isVintage
    }
}

public enum CollectionType2: String, Codable, Sendable {
    case personal = "personal"
    case resale = "resale"
}

public struct RecommendBatchResponse: Codable, Sendable {
    public let results: [RecommendBatchResult]

    public init(results: [RecommendBatchResult]) {
        self.results = results
    }
}

public struct RecommendBatchResult: Codable, Sendable {
    public let id: String
    public let route: RecommendedRoute?
    public let alternatives: [Alternative]
    public let economics: Economics?
    public let assumptions: [String]
    public let explanation: String?
    public let confidence: GameConfidence?
    public let calculationVersion: String?
    public let priceSource: String?
    public let priceConfidence: GameConfidence?
    public let currencyNote: String?

    enum CodingKeys: String, CodingKey {
        case id
        case route
        case alternatives
        case economics
        case assumptions
        case explanation
        case confidence
        case calculationVersion = "calculation_version"
        case priceSource
        case priceConfidence
        case currencyNote
    }

    public init(id: String, route: RecommendedRoute?, alternatives: [Alternative], economics: Economics?, assumptions: [String], explanation: String?, confidence: GameConfidence?, calculationVersion: String?, priceSource: String?, priceConfidence: GameConfidence?, currencyNote: String?) {
        self.id = id
        self.route = route
        self.alternatives = alternatives
        self.economics = economics
        self.assumptions = assumptions
        self.explanation = explanation
        self.confidence = confidence
        self.calculationVersion = calculationVersion
        self.priceSource = priceSource
        self.priceConfidence = priceConfidence
        self.currencyNote = currencyNote
    }
}

public struct CardSearchRequest: Codable, Sendable {
    public let q: String
    public let game: String?

    public init(q: String, game: String?) {
        self.q = q
        self.game = game
    }
}

public struct CardSearchResponse: Codable, Sendable {
    public let results: [CardSearchResult]

    public init(results: [CardSearchResult]) {
        self.results = results
    }
}

public struct CardSearchResult: Codable, Sendable {
    public let tcgId: String
    public let name: String
    public let setName: String?
    public let number: String?
    public let rarity: String?
    public let image: String?
    public let marketGbp: Double?
    public let game: String?
    public let gameDisplayName: String?
    public let printingCount: Int?
    public let printings: [Printing]?

    public init(tcgId: String, name: String, setName: String?, number: String?, rarity: String?, image: String?, marketGbp: Double?, game: String?, gameDisplayName: String?, printingCount: Int?, printings: [Printing]?) {
        self.tcgId = tcgId
        self.name = name
        self.setName = setName
        self.number = number
        self.rarity = rarity
        self.image = image
        self.marketGbp = marketGbp
        self.game = game
        self.gameDisplayName = gameDisplayName
        self.printingCount = printingCount
        self.printings = printings
    }
}

public struct Printing: Codable, Sendable {
    public let tcgId: String
    public let setName: String?
    public let number: String?
    public let rarity: String?
    public let image: String?
    public let marketGbp: Double?

    public init(tcgId: String, setName: String?, number: String?, rarity: String?, image: String?, marketGbp: Double?) {
        self.tcgId = tcgId
        self.setName = setName
        self.number = number
        self.rarity = rarity
        self.image = image
        self.marketGbp = marketGbp
    }
}

public struct PriceRequest: Codable, Sendable {
    public let name: String
    public let setName: String
    public let cardNumber: String
    public let condition: String?
    public let tcgId: String?
    public let tcgBaseline: TcgBaseline?
    public let noCache: Bool?

    enum CodingKeys: String, CodingKey {
        case name
        case setName = "set_name"
        case cardNumber = "card_number"
        case condition
        case tcgId = "tcg_id"
        case tcgBaseline
        case noCache
    }

    public init(name: String, setName: String, cardNumber: String, condition: String?, tcgId: String?, tcgBaseline: TcgBaseline?, noCache: Bool?) {
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.condition = condition
        self.tcgId = tcgId
        self.tcgBaseline = tcgBaseline
        self.noCache = noCache
    }
}

public struct TcgBaseline: Codable, Sendable {
    public let tcpMarketUsd: Double?
    public let cmTrendEur: Double?

    enum CodingKeys: String, CodingKey {
        case tcpMarketUsd = "tcp_market_usd"
        case cmTrendEur = "cm_trend_eur"
    }

    public init(tcpMarketUsd: Double?, cmTrendEur: Double?) {
        self.tcpMarketUsd = tcpMarketUsd
        self.cmTrendEur = cmTrendEur
    }
}

public struct PriceResponse: Codable, Sendable {
    public let low: Double?
    public let avg: Double?
    public let top: Double?
    public let priceSource: String?
    public let provider: String?
    public let fxRate: Double?
    public let fxDate: String?
    public let saleCount: Int?
    public let approxSaleCount: Bool?
    public let comps: [[String: JSONValue]]?
    public let confidence: GameConfidence?
    public let priceWarning: String?
    public let cached: Bool?
    public let stale: Bool?
    public let fetchedAt: String?
    public let error: String?

    enum CodingKeys: String, CodingKey {
        case low
        case avg
        case top
        case priceSource = "price_source"
        case provider
        case fxRate = "fx_rate"
        case fxDate = "fx_date"
        case saleCount = "sale_count"
        case approxSaleCount = "approx_sale_count"
        case comps
        case confidence
        case priceWarning = "price_warning"
        case cached
        case stale
        case fetchedAt = "fetched_at"
        case error
    }

    public init(low: Double?, avg: Double?, top: Double?, priceSource: String?, provider: String?, fxRate: Double?, fxDate: String?, saleCount: Int?, approxSaleCount: Bool?, comps: [[String: JSONValue]]?, confidence: GameConfidence?, priceWarning: String?, cached: Bool?, stale: Bool?, fetchedAt: String?, error: String?) {
        self.low = low
        self.avg = avg
        self.top = top
        self.priceSource = priceSource
        self.provider = provider
        self.fxRate = fxRate
        self.fxDate = fxDate
        self.saleCount = saleCount
        self.approxSaleCount = approxSaleCount
        self.comps = comps
        self.confidence = confidence
        self.priceWarning = priceWarning
        self.cached = cached
        self.stale = stale
        self.fetchedAt = fetchedAt
        self.error = error
    }
}

public struct CertLookupRequest: Codable, Sendable {
    public let grader: Grader
    public let certNumber: String

    public init(grader: Grader, certNumber: String) {
        self.grader = grader
        self.certNumber = certNumber
    }
}

public enum Grader: String, Codable, Sendable {
    case pSA = "PSA"
}

public struct CertLookupResponse: Codable, Sendable {
    public let found: Bool
    public let grader: Grader2
    public let certNumber: String
    public let grade: String?
    public let gradeDescription: String?
    public let subject: String?
    public let year: String?
    public let brand: String?
    public let category: String?
    public let cardNumber: String?
    public let variety: String?
    public let labelType: String?

    public init(found: Bool, grader: Grader2, certNumber: String, grade: String?, gradeDescription: String?, subject: String?, year: String?, brand: String?, category: String?, cardNumber: String?, variety: String?, labelType: String?) {
        self.found = found
        self.grader = grader
        self.certNumber = certNumber
        self.grade = grade
        self.gradeDescription = gradeDescription
        self.subject = subject
        self.year = year
        self.brand = brand
        self.category = category
        self.cardNumber = cardNumber
        self.variety = variety
        self.labelType = labelType
    }
}

public enum Grader2: String, Codable, Sendable {
    case pSA = "PSA"
}

public struct ChannelListingRequest: Codable, Sendable {
    public let channel: Channel
    public let cardRef: String
    public let priceGbp: Double
    public let condition: String

    public init(channel: Channel, cardRef: String, priceGbp: Double, condition: String) {
        self.channel = channel
        self.cardRef = cardRef
        self.priceGbp = priceGbp
        self.condition = condition
    }
}

public enum Channel: String, Codable, Sendable {
    case cardtrader = "cardtrader"
}

public struct ChannelListingResponse: Codable, Sendable {
    public let channel: Channel
    public let channelListingId: String?
    public let url: String?
    public let status: Status
    public let error: String?

    public init(channel: Channel, channelListingId: String?, url: String?, status: Status, error: String?) {
        self.channel = channel
        self.channelListingId = channelListingId
        self.url = url
        self.status = status
        self.error = error
    }
}

public enum Status: String, Codable, Sendable {
    case listed = "listed"
    case failed = "failed"
}

public struct CatalogueLookupRequest: Codable, Sendable {
    public let game: Game?
    public let name: String?
    public let collectorNumber: String?
    public let setCode: String?

    public init(game: Game?, name: String?, collectorNumber: String?, setCode: String?) {
        self.game = game
        self.name = name
        self.collectorNumber = collectorNumber
        self.setCode = setCode
    }
}

public struct CatalogueLookupResponse: Codable, Sendable {
    public let match: CatalogueLookupMatch?
    public let confidence: GameConfidence?
    public let candidates: [CatalogueLookupMatch]

    public init(match: CatalogueLookupMatch?, confidence: GameConfidence?, candidates: [CatalogueLookupMatch]) {
        self.match = match
        self.confidence = confidence
        self.candidates = candidates
    }
}

public struct Entitlement: Codable, Sendable {
    public let userId: String
    public let tier: Tier2
    public let status: Status2
    public let source: Source2
    public let currentPeriodEnd: String
    public let cancelAtPeriodEnd: Bool
    public let trialEnd: String?
    public let updatedAt: String

    public init(userId: String, tier: Tier2, status: Status2, source: Source2, currentPeriodEnd: String, cancelAtPeriodEnd: Bool, trialEnd: String?, updatedAt: String) {
        self.userId = userId
        self.tier = tier
        self.status = status
        self.source = source
        self.currentPeriodEnd = currentPeriodEnd
        self.cancelAtPeriodEnd = cancelAtPeriodEnd
        self.trialEnd = trialEnd
        self.updatedAt = updatedAt
    }
}

public enum Tier2: String, Codable, Sendable {
    case free = "free"
    case starter = "starter"
    case growth = "growth"
    case pro = "pro"
}

public enum Status2: String, Codable, Sendable {
    case active = "active"
    case trialing = "trialing"
    case pastDue = "past_due"
    case grace = "grace"
    case canceled = "canceled"
    case expired = "expired"
}

public enum Source2: String, Codable, Sendable {
    case stripe = "stripe"
    case apple = "apple"
}

public struct VerificationEventRequest: Codable, Sendable {
    public let physicalCardId: String
    public let kind: Kind
    public let field: String
    public let verdict: Verdict?
    public let previousValue: String?
    public let correctedValue: String?
    public let source: Source3?

    public init(physicalCardId: String, kind: Kind, field: String, verdict: Verdict?, previousValue: String?, correctedValue: String?, source: Source3?) {
        self.physicalCardId = physicalCardId
        self.kind = kind
        self.field = field
        self.verdict = verdict
        self.previousValue = previousValue
        self.correctedValue = correctedValue
        self.source = source
    }
}

public enum Kind: String, Codable, Sendable {
    case identity = "identity"
    case condition = "condition"
}

public enum Verdict: String, Codable, Sendable {
    case confirmed = "confirmed"
    case notPresent = "not_present"
    case unsure = "unsure"
}

public enum Source3: String, Codable, Sendable {
    case iosCapture = "ios_capture"
    case webAddFlow = "web_add_flow"
    case other = "other"
}

public struct VerificationEventResponse: Codable, Sendable {
    public let recorded: Bool
    public let id: String?

    public init(recorded: Bool, id: String?) {
        self.recorded = recorded
        self.id = id
    }
}

public struct InspectionDepthHintRequest: Codable, Sendable {
    public let name: String
    public let setName: String?
    public let cardNumber: String?
    public let game: Game?
    public let tcgId: String?

    public init(name: String, setName: String?, cardNumber: String?, game: Game?, tcgId: String?) {
        self.name = name
        self.setName = setName
        self.cardNumber = cardNumber
        self.game = game
        self.tcgId = tcgId
    }
}

public struct InspectionDepthHintResponse: Codable, Sendable {
    public let depthTier: DepthTier
    public let rationale: String
    public let confidence: Confidence

    public init(depthTier: DepthTier, rationale: String, confidence: Confidence) {
        self.depthTier = depthTier
        self.rationale = rationale
        self.confidence = confidence
    }
}

public enum DepthTier: String, Codable, Sendable {
    case minimal = "minimal"
    case standard = "standard"
    case thorough = "thorough"
}

public enum Confidence: String, Codable, Sendable {
    case high = "high"
    case medium = "medium"
    case low = "low"
}

public struct SignedPhotoUrlRequest: Codable, Sendable {
    public let urls: [String]
    public let ttlSeconds: Int?

    public init(urls: [String], ttlSeconds: Int?) {
        self.urls = urls
        self.ttlSeconds = ttlSeconds
    }
}

public struct SignedPhotoUrlResponse: Codable, Sendable {
    public let results: [SignedPhotoUrlResult]

    public init(results: [SignedPhotoUrlResult]) {
        self.results = results
    }
}

public struct SignedPhotoUrlResult: Codable, Sendable {
    public let url: String
    public let signedUrl: String?
    public let error: String?

    public init(url: String, signedUrl: String?, error: String?) {
        self.url = url
        self.signedUrl = signedUrl
        self.error = error
    }
}

public struct PricingRule: Codable, Sendable {
    public let id: String
    public let name: String
    public let active: Bool
    public let scopeGame: [String]
    public let scopeSet: [String]
    public let scopeCondition: [String]
    public let conditionMultipliers: [String: Double]
    public let rounding: Rounding
    public let minPriceGbp: Double?
    public let maxPriceGbp: Double?
    public let createdAt: String
    public let updatedAt: String

    public init(id: String, name: String, active: Bool, scopeGame: [String], scopeSet: [String], scopeCondition: [String], conditionMultipliers: [String: Double], rounding: Rounding, minPriceGbp: Double?, maxPriceGbp: Double?, createdAt: String, updatedAt: String) {
        self.id = id
        self.name = name
        self.active = active
        self.scopeGame = scopeGame
        self.scopeSet = scopeSet
        self.scopeCondition = scopeCondition
        self.conditionMultipliers = conditionMultipliers
        self.rounding = rounding
        self.minPriceGbp = minPriceGbp
        self.maxPriceGbp = maxPriceGbp
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

public enum Rounding: String, Codable, Sendable {
    case none = "none"
    case nearest10p = "nearest_10p"
    case nearest50p = "nearest_50p"
    case nearestPound = "nearest_pound"
    case charm99 = "charm_99"
}

public struct PricingRuleInput: Codable, Sendable {
    public let name: String
    public let active: Bool?
    public let scopeGame: [String]
    public let scopeSet: [String]
    public let scopeCondition: [String]
    public let conditionMultipliers: [String: Double]
    public let rounding: Rounding
    public let minPriceGbp: Double?
    public let maxPriceGbp: Double?

    public init(name: String, active: Bool?, scopeGame: [String], scopeSet: [String], scopeCondition: [String], conditionMultipliers: [String: Double], rounding: Rounding, minPriceGbp: Double?, maxPriceGbp: Double?) {
        self.name = name
        self.active = active
        self.scopeGame = scopeGame
        self.scopeSet = scopeSet
        self.scopeCondition = scopeCondition
        self.conditionMultipliers = conditionMultipliers
        self.rounding = rounding
        self.minPriceGbp = minPriceGbp
        self.maxPriceGbp = maxPriceGbp
    }
}

public struct PricingRuleListResponse: Codable, Sendable {
    public let rules: [PricingRule]

    public init(rules: [PricingRule]) {
        self.rules = rules
    }
}

public struct ListingTemplate: Codable, Sendable {
    public let id: String
    public let name: String
    public let active: Bool
    public let scopeGame: [String]
    public let scopeSet: [String]
    public let titlePattern: String
    public let descriptionPattern: String?
    public let createdAt: String
    public let updatedAt: String

    public init(id: String, name: String, active: Bool, scopeGame: [String], scopeSet: [String], titlePattern: String, descriptionPattern: String?, createdAt: String, updatedAt: String) {
        self.id = id
        self.name = name
        self.active = active
        self.scopeGame = scopeGame
        self.scopeSet = scopeSet
        self.titlePattern = titlePattern
        self.descriptionPattern = descriptionPattern
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

public struct ListingTemplateInput: Codable, Sendable {
    public let name: String
    public let active: Bool?
    public let scopeGame: [String]
    public let scopeSet: [String]
    public let titlePattern: String
    public let descriptionPattern: String?

    public init(name: String, active: Bool?, scopeGame: [String], scopeSet: [String], titlePattern: String, descriptionPattern: String?) {
        self.name = name
        self.active = active
        self.scopeGame = scopeGame
        self.scopeSet = scopeSet
        self.titlePattern = titlePattern
        self.descriptionPattern = descriptionPattern
    }
}

public struct ListingTemplateListResponse: Codable, Sendable {
    public let templates: [ListingTemplate]

    public init(templates: [ListingTemplate]) {
        self.templates = templates
    }
}

public struct PricingBreakdownRequest: Codable, Sendable {
    public let price: Double
    public let purchaseCost: Double
    public let marketMedian: Double
    public let collectionType: CollectionType3?
    public let priceSource: String?
    public let settings: PricingSettings?

    public init(price: Double, purchaseCost: Double, marketMedian: Double, collectionType: CollectionType3?, priceSource: String?, settings: PricingSettings?) {
        self.price = price
        self.purchaseCost = purchaseCost
        self.marketMedian = marketMedian
        self.collectionType = collectionType
        self.priceSource = priceSource
        self.settings = settings
    }
}

public enum CollectionType3: String, Codable, Sendable {
    case personal = "personal"
    case resale = "resale"
}

public struct PricingBreakdownResponse: Codable, Sendable {
    public let purchaseCost: Double
    public let marketMedian: Double
    public let suggestedPrice: Double
    public let ebayFee: Double
    public let packagingCost: Double
    public let shippingCost: Double
    public let grossProfit: Double
    public let taxProvision: Double
    public let netProfit: Double
    public let netMarginPct: Double
    public let minViablePrice: Double
    public let isMarketBelowMin: Bool
    public let warningMsg: String?
    public let priceKind: PriceKind

    public init(purchaseCost: Double, marketMedian: Double, suggestedPrice: Double, ebayFee: Double, packagingCost: Double, shippingCost: Double, grossProfit: Double, taxProvision: Double, netProfit: Double, netMarginPct: Double, minViablePrice: Double, isMarketBelowMin: Bool, warningMsg: String?, priceKind: PriceKind) {
        self.purchaseCost = purchaseCost
        self.marketMedian = marketMedian
        self.suggestedPrice = suggestedPrice
        self.ebayFee = ebayFee
        self.packagingCost = packagingCost
        self.shippingCost = shippingCost
        self.grossProfit = grossProfit
        self.taxProvision = taxProvision
        self.netProfit = netProfit
        self.netMarginPct = netMarginPct
        self.minViablePrice = minViablePrice
        self.isMarketBelowMin = isMarketBelowMin
        self.warningMsg = warningMsg
        self.priceKind = priceKind
    }
}

public enum PriceKind: String, Codable, Sendable {
    case realised = "realised"
    case asking = "asking"
}

public struct ProfileResponse: Codable, Sendable {
    public let sellerType: SellerType
    public let sellerTypeSource: SellerTypeSource
    public let dispatchAddress: DispatchAddress
    public let agedInventoryDays: Int
    public let pricingSettings: StoredPricingSettings
    public let effectivePricingSettings: PricingSettings
    public let isAdmin: Bool

    public init(sellerType: SellerType, sellerTypeSource: SellerTypeSource, dispatchAddress: DispatchAddress, agedInventoryDays: Int, pricingSettings: StoredPricingSettings, effectivePricingSettings: PricingSettings, isAdmin: Bool) {
        self.sellerType = sellerType
        self.sellerTypeSource = sellerTypeSource
        self.dispatchAddress = dispatchAddress
        self.agedInventoryDays = agedInventoryDays
        self.pricingSettings = pricingSettings
        self.effectivePricingSettings = effectivePricingSettings
        self.isAdmin = isAdmin
    }
}

public enum SellerType: String, Codable, Sendable {
    case `private` = "private"
    case business = "business"
}

public enum SellerTypeSource: String, Codable, Sendable {
    case manual = "manual"
    case auto = "auto"
}

public struct DispatchAddress: Codable, Sendable {
    public let line1: String?
    public let city: String?
    public let postcode: String?
    public let country: String

    public init(line1: String?, city: String?, postcode: String?, country: String) {
        self.line1 = line1
        self.city = city
        self.postcode = postcode
        self.country = country
    }
}

public struct StoredPricingSettings: Codable, Sendable {
    public let ebayFeeRate: Double?
    public let ebayFeeFixed: Double?
    public let packagingCost: Double
    public let shippingCost: Double
    public let taxRate: Double
    public let minProfitPct: Double
    public let minSaleValue: Double
    public let postageCost: Double

    public init(ebayFeeRate: Double?, ebayFeeFixed: Double?, packagingCost: Double, shippingCost: Double, taxRate: Double, minProfitPct: Double, minSaleValue: Double, postageCost: Double) {
        self.ebayFeeRate = ebayFeeRate
        self.ebayFeeFixed = ebayFeeFixed
        self.packagingCost = packagingCost
        self.shippingCost = shippingCost
        self.taxRate = taxRate
        self.minProfitPct = minProfitPct
        self.minSaleValue = minSaleValue
        self.postageCost = postageCost
    }
}

public struct ProfilePatch: Codable, Sendable {
    public let sellerType: SellerType?
    public let dispatchAddress: DispatchAddressPatch?
    public let agedInventoryDays: Int?
    public let pricingSettings: StoredPricingSettingsPatch?

    public init(sellerType: SellerType?, dispatchAddress: DispatchAddressPatch?, agedInventoryDays: Int?, pricingSettings: StoredPricingSettingsPatch?) {
        self.sellerType = sellerType
        self.dispatchAddress = dispatchAddress
        self.agedInventoryDays = agedInventoryDays
        self.pricingSettings = pricingSettings
    }
}

public struct DispatchAddressPatch: Codable, Sendable {
    public let line1: String?
    public let city: String?
    public let postcode: String?
    public let country: String?

    public init(line1: String?, city: String?, postcode: String?, country: String?) {
        self.line1 = line1
        self.city = city
        self.postcode = postcode
        self.country = country
    }
}

public struct StoredPricingSettingsPatch: Codable, Sendable {
    public let ebayFeeRate: Double?
    public let ebayFeeFixed: Double?
    public let packagingCost: Double?
    public let shippingCost: Double?
    public let taxRate: Double?
    public let minProfitPct: Double?
    public let minSaleValue: Double?
    public let postageCost: Double?

    public init(ebayFeeRate: Double?, ebayFeeFixed: Double?, packagingCost: Double?, shippingCost: Double?, taxRate: Double?, minProfitPct: Double?, minSaleValue: Double?, postageCost: Double?) {
        self.ebayFeeRate = ebayFeeRate
        self.ebayFeeFixed = ebayFeeFixed
        self.packagingCost = packagingCost
        self.shippingCost = shippingCost
        self.taxRate = taxRate
        self.minProfitPct = minProfitPct
        self.minSaleValue = minSaleValue
        self.postageCost = postageCost
    }
}
