// AUTO-GENERATED by scripts/gen-swift-db.ts from src/db/database.types.ts — do not edit by hand.
// Regenerate via `npm run build`. See README.md "Releasing a new version".

import Foundation

/// Mirrors the TS `Json` union for jsonb columns (payload, defects, comps, ...).
public enum JSONValue: Codable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null; return }
        if let v = try? container.decode(Bool.self) { self = .bool(v); return }
        if let v = try? container.decode(Double.self) { self = .number(v); return }
        if let v = try? container.decode(String.self) { self = .string(v); return }
        if let v = try? container.decode([String: JSONValue].self) { self = .object(v); return }
        if let v = try? container.decode([JSONValue].self) { self = .array(v); return }
        throw DecodingError.typeMismatch(JSONValue.self, .init(codingPath: decoder.codingPath, debugDescription: "Unsupported JSON value"))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let v): try container.encode(v)
        case .number(let v): try container.encode(v)
        case .bool(let v): try container.encode(v)
        case .object(let v): try container.encode(v)
        case .array(let v): try container.encode(v)
        case .null: try container.encodeNil()
        }
    }
}

/// Row shape for `public.audit_events`. Generated from database.types.ts — do not edit by hand.
public struct AuditEventsRow: Codable, Sendable, Identifiable {
    public let accountId: String?
    public let createdAt: String
    public let entityId: String
    public let entityType: String
    public let eventType: String
    public let id: String
    public let payload: JSONValue
    public let userAgent: String?

    enum CodingKeys: String, CodingKey {
        case accountId = "account_id"
        case createdAt = "created_at"
        case entityId = "entity_id"
        case entityType = "entity_type"
        case eventType = "event_type"
        case id
        case payload
        case userAgent = "user_agent"
    }

    public init(accountId: String?, createdAt: String, entityId: String, entityType: String, eventType: String, id: String, payload: JSONValue, userAgent: String?) {
        self.accountId = accountId
        self.createdAt = createdAt
        self.entityId = entityId
        self.entityType = entityType
        self.eventType = eventType
        self.id = id
        self.payload = payload
        self.userAgent = userAgent
    }
}

/// Row shape for `public.catalogue_cards`. Generated from database.types.ts — do not edit by hand.
public struct CatalogueCardsRow: Codable, Sendable, Identifiable {
    public let attributes: [String]
    public let cardNumber: String?
    public let createdAt: String
    public let finishes: [String]
    public let game: String
    public let id: String
    public let imageRef: String?
    public let isPromo: Bool
    public let language: String
    public let listingDescTemplate: String?
    public let listingTitleTemplate: String?
    public let name: String
    public let nameConfidence: Double?
    public let nativeCatalogueId: String?
    public let normalizedName: String?
    public let normalizedNumber: String?
    public let rarity: String?
    public let scryfallId: String?
    public let setConfidence: Double?
    public let setName: String?
    public let source: String?
    public let tcgId: String?
    public let tcgplayerId: String?
    public let updatedAt: String
    public let verifiedAt: String?

    enum CodingKeys: String, CodingKey {
        case attributes
        case cardNumber = "card_number"
        case createdAt = "created_at"
        case finishes
        case game
        case id
        case imageRef = "image_ref"
        case isPromo = "is_promo"
        case language
        case listingDescTemplate = "listing_desc_template"
        case listingTitleTemplate = "listing_title_template"
        case name
        case nameConfidence = "name_confidence"
        case nativeCatalogueId = "native_catalogue_id"
        case normalizedName = "normalized_name"
        case normalizedNumber = "normalized_number"
        case rarity
        case scryfallId = "scryfall_id"
        case setConfidence = "set_confidence"
        case setName = "set_name"
        case source
        case tcgId = "tcg_id"
        case tcgplayerId = "tcgplayer_id"
        case updatedAt = "updated_at"
        case verifiedAt = "verified_at"
    }

    public init(attributes: [String], cardNumber: String?, createdAt: String, finishes: [String], game: String, id: String, imageRef: String?, isPromo: Bool, language: String, listingDescTemplate: String?, listingTitleTemplate: String?, name: String, nameConfidence: Double?, nativeCatalogueId: String?, normalizedName: String?, normalizedNumber: String?, rarity: String?, scryfallId: String?, setConfidence: Double?, setName: String?, source: String?, tcgId: String?, tcgplayerId: String?, updatedAt: String, verifiedAt: String?) {
        self.attributes = attributes
        self.cardNumber = cardNumber
        self.createdAt = createdAt
        self.finishes = finishes
        self.game = game
        self.id = id
        self.imageRef = imageRef
        self.isPromo = isPromo
        self.language = language
        self.listingDescTemplate = listingDescTemplate
        self.listingTitleTemplate = listingTitleTemplate
        self.name = name
        self.nameConfidence = nameConfidence
        self.nativeCatalogueId = nativeCatalogueId
        self.normalizedName = normalizedName
        self.normalizedNumber = normalizedNumber
        self.rarity = rarity
        self.scryfallId = scryfallId
        self.setConfidence = setConfidence
        self.setName = setName
        self.source = source
        self.tcgId = tcgId
        self.tcgplayerId = tcgplayerId
        self.updatedAt = updatedAt
        self.verifiedAt = verifiedAt
    }
}

/// Row shape for `public.catalogue_sets`. Generated from database.types.ts — do not edit by hand.
public struct CatalogueSetsRow: Codable, Sendable, Identifiable {
    public let cardCount: Int?
    public let game: String
    public let id: String
    public let ingestedAt: String
    public let setCode: String
    public let setName: String
    public let source: String

    enum CodingKeys: String, CodingKey {
        case cardCount = "card_count"
        case game
        case id
        case ingestedAt = "ingested_at"
        case setCode = "set_code"
        case setName = "set_name"
        case source
    }

    public init(cardCount: Int?, game: String, id: String, ingestedAt: String, setCode: String, setName: String, source: String) {
        self.cardCount = cardCount
        self.game = game
        self.id = id
        self.ingestedAt = ingestedAt
        self.setCode = setCode
        self.setName = setName
        self.source = source
    }
}

/// Row shape for `public.condition_assessments`. Generated from database.types.ts — do not edit by hand.
public struct ConditionAssessmentsRow: Codable, Sendable, Identifiable {
    public let assessmentVersion: Int
    public let centeringRatios: JSONValue?
    public let confidence: String?
    public let createdAt: String
    public let defects: JSONValue
    public let id: String
    public let imageQuality: JSONValue?
    public let isCurrent: Bool
    public let modelVersion: String?
    public let physicalCardId: String
    public let sellerConfirmedCondition: String?
    public let suggestedCondition: String?

    enum CodingKeys: String, CodingKey {
        case assessmentVersion = "assessment_version"
        case centeringRatios = "centering_ratios"
        case confidence
        case createdAt = "created_at"
        case defects
        case id
        case imageQuality = "image_quality"
        case isCurrent = "is_current"
        case modelVersion = "model_version"
        case physicalCardId = "physical_card_id"
        case sellerConfirmedCondition = "seller_confirmed_condition"
        case suggestedCondition = "suggested_condition"
    }

    public init(assessmentVersion: Int, centeringRatios: JSONValue?, confidence: String?, createdAt: String, defects: JSONValue, id: String, imageQuality: JSONValue?, isCurrent: Bool, modelVersion: String?, physicalCardId: String, sellerConfirmedCondition: String?, suggestedCondition: String?) {
        self.assessmentVersion = assessmentVersion
        self.centeringRatios = centeringRatios
        self.confidence = confidence
        self.createdAt = createdAt
        self.defects = defects
        self.id = id
        self.imageQuality = imageQuality
        self.isCurrent = isCurrent
        self.modelVersion = modelVersion
        self.physicalCardId = physicalCardId
        self.sellerConfirmedCondition = sellerConfirmedCondition
        self.suggestedCondition = suggestedCondition
    }
}

/// Row shape for `public.physical_cards`. Generated from database.types.ts — do not edit by hand.
public struct PhysicalCardsRow: Codable, Sendable, Identifiable {
    public let accountId: String
    public let acquisitionId: String?
    public let allocationChannel: String?
    public let allocationRefId: String?
    public let attributes: [String]
    public let batchPosition: Int?
    public let cardNumber: String?
    public let catalogueCardId: String?
    public let certNumber: String?
    public let cmTrendEur: Double?
    public let collectionType: String
    public let condition: String?
    public let conditionSource: String?
    public let createdAt: String
    public let decidedRoute: String?
    public let ebayListingId: String?
    public let ebayOfferId: String?
    public let ebayPriceAvg: Double?
    public let ebayPriceLow: Double?
    public let ebayPriceTop: Double?
    public let fxRateEurGbp: Double?
    public let fxRateUsdGbp: Double?
    public let game: String
    public let grade: String?
    public let gradingCompany: String?
    public let id: String
    public let idVerifiedBySeller: Bool
    public let isGraded: Bool
    public let isPromo: Bool
    public let language: String
    public let legacyCardId: String?
    public let listingDescription: String?
    public let listingTitle: String?
    public let name: String?
    public let nameConfidence: Double?
    public let notes: String?
    public let photoThumbUrls: [String]
    public let photoUrls: [String]
    public let purchaseCost: Double?
    public let rarity: String?
    public let saleFees: Double?
    public let salePlatform: String?
    public let salePrice: Double?
    public let scanBatchId: String?
    public let setConfidence: Double?
    public let setName: String?
    public let sku: String?
    public let soldAt: String?
    public let status: String
    public let storageLocation: String?
    public let suggestedPrice: Double?
    public let tcgId: String?
    public let tcpMarketUsd: Double?

    enum CodingKeys: String, CodingKey {
        case accountId = "account_id"
        case acquisitionId = "acquisition_id"
        case allocationChannel = "allocation_channel"
        case allocationRefId = "allocation_ref_id"
        case attributes
        case batchPosition = "batch_position"
        case cardNumber = "card_number"
        case catalogueCardId = "catalogue_card_id"
        case certNumber = "cert_number"
        case cmTrendEur = "cm_trend_eur"
        case collectionType = "collection_type"
        case condition
        case conditionSource = "condition_source"
        case createdAt = "created_at"
        case decidedRoute = "decided_route"
        case ebayListingId = "ebay_listing_id"
        case ebayOfferId = "ebay_offer_id"
        case ebayPriceAvg = "ebay_price_avg"
        case ebayPriceLow = "ebay_price_low"
        case ebayPriceTop = "ebay_price_top"
        case fxRateEurGbp = "fx_rate_eur_gbp"
        case fxRateUsdGbp = "fx_rate_usd_gbp"
        case game
        case grade
        case gradingCompany = "grading_company"
        case id
        case idVerifiedBySeller = "id_verified_by_seller"
        case isGraded = "is_graded"
        case isPromo = "is_promo"
        case language
        case legacyCardId = "legacy_card_id"
        case listingDescription = "listing_description"
        case listingTitle = "listing_title"
        case name
        case nameConfidence = "name_confidence"
        case notes
        case photoThumbUrls = "photo_thumb_urls"
        case photoUrls = "photo_urls"
        case purchaseCost = "purchase_cost"
        case rarity
        case saleFees = "sale_fees"
        case salePlatform = "sale_platform"
        case salePrice = "sale_price"
        case scanBatchId = "scan_batch_id"
        case setConfidence = "set_confidence"
        case setName = "set_name"
        case sku
        case soldAt = "sold_at"
        case status
        case storageLocation = "storage_location"
        case suggestedPrice = "suggested_price"
        case tcgId = "tcg_id"
        case tcpMarketUsd = "tcp_market_usd"
    }

    public init(accountId: String, acquisitionId: String?, allocationChannel: String?, allocationRefId: String?, attributes: [String], batchPosition: Int?, cardNumber: String?, catalogueCardId: String?, certNumber: String?, cmTrendEur: Double?, collectionType: String, condition: String?, conditionSource: String?, createdAt: String, decidedRoute: String?, ebayListingId: String?, ebayOfferId: String?, ebayPriceAvg: Double?, ebayPriceLow: Double?, ebayPriceTop: Double?, fxRateEurGbp: Double?, fxRateUsdGbp: Double?, game: String, grade: String?, gradingCompany: String?, id: String, idVerifiedBySeller: Bool, isGraded: Bool, isPromo: Bool, language: String, legacyCardId: String?, listingDescription: String?, listingTitle: String?, name: String?, nameConfidence: Double?, notes: String?, photoThumbUrls: [String], photoUrls: [String], purchaseCost: Double?, rarity: String?, saleFees: Double?, salePlatform: String?, salePrice: Double?, scanBatchId: String?, setConfidence: Double?, setName: String?, sku: String?, soldAt: String?, status: String, storageLocation: String?, suggestedPrice: Double?, tcgId: String?, tcpMarketUsd: Double?) {
        self.accountId = accountId
        self.acquisitionId = acquisitionId
        self.allocationChannel = allocationChannel
        self.allocationRefId = allocationRefId
        self.attributes = attributes
        self.batchPosition = batchPosition
        self.cardNumber = cardNumber
        self.catalogueCardId = catalogueCardId
        self.certNumber = certNumber
        self.cmTrendEur = cmTrendEur
        self.collectionType = collectionType
        self.condition = condition
        self.conditionSource = conditionSource
        self.createdAt = createdAt
        self.decidedRoute = decidedRoute
        self.ebayListingId = ebayListingId
        self.ebayOfferId = ebayOfferId
        self.ebayPriceAvg = ebayPriceAvg
        self.ebayPriceLow = ebayPriceLow
        self.ebayPriceTop = ebayPriceTop
        self.fxRateEurGbp = fxRateEurGbp
        self.fxRateUsdGbp = fxRateUsdGbp
        self.game = game
        self.grade = grade
        self.gradingCompany = gradingCompany
        self.id = id
        self.idVerifiedBySeller = idVerifiedBySeller
        self.isGraded = isGraded
        self.isPromo = isPromo
        self.language = language
        self.legacyCardId = legacyCardId
        self.listingDescription = listingDescription
        self.listingTitle = listingTitle
        self.name = name
        self.nameConfidence = nameConfidence
        self.notes = notes
        self.photoThumbUrls = photoThumbUrls
        self.photoUrls = photoUrls
        self.purchaseCost = purchaseCost
        self.rarity = rarity
        self.saleFees = saleFees
        self.salePlatform = salePlatform
        self.salePrice = salePrice
        self.scanBatchId = scanBatchId
        self.setConfidence = setConfidence
        self.setName = setName
        self.sku = sku
        self.soldAt = soldAt
        self.status = status
        self.storageLocation = storageLocation
        self.suggestedPrice = suggestedPrice
        self.tcgId = tcgId
        self.tcpMarketUsd = tcpMarketUsd
    }
}

/// Row shape for `public.profiles`. Generated from database.types.ts — do not edit by hand.
public struct ProfilesRow: Codable, Sendable, Identifiable {
    public let agedInventoryDays: Int
    public let createdAt: String?
    public let dispatchAddressCity: String?
    public let dispatchAddressCountry: String
    public let dispatchAddressLine1: String?
    public let dispatchAddressPostcode: String?
    public let id: String
    public let isAdmin: Bool
    public let sellerType: String
    public let sellerTypeSource: String

    enum CodingKeys: String, CodingKey {
        case agedInventoryDays = "aged_inventory_days"
        case createdAt = "created_at"
        case dispatchAddressCity = "dispatch_address_city"
        case dispatchAddressCountry = "dispatch_address_country"
        case dispatchAddressLine1 = "dispatch_address_line1"
        case dispatchAddressPostcode = "dispatch_address_postcode"
        case id
        case isAdmin = "is_admin"
        case sellerType = "seller_type"
        case sellerTypeSource = "seller_type_source"
    }

    public init(agedInventoryDays: Int, createdAt: String?, dispatchAddressCity: String?, dispatchAddressCountry: String, dispatchAddressLine1: String?, dispatchAddressPostcode: String?, id: String, isAdmin: Bool, sellerType: String, sellerTypeSource: String) {
        self.agedInventoryDays = agedInventoryDays
        self.createdAt = createdAt
        self.dispatchAddressCity = dispatchAddressCity
        self.dispatchAddressCountry = dispatchAddressCountry
        self.dispatchAddressLine1 = dispatchAddressLine1
        self.dispatchAddressPostcode = dispatchAddressPostcode
        self.id = id
        self.isAdmin = isAdmin
        self.sellerType = sellerType
        self.sellerTypeSource = sellerTypeSource
    }
}

/// Row shape for `public.scan_items`. Generated from database.types.ts — do not edit by hand.
public struct ScanItemsRow: Codable, Sendable, Identifiable {
    public let batchId: String
    public let createdAt: String
    public let id: String
    public let physicalCardId: String?
    public let publicUrl: String?
    public let side: String?
    public let sortOrder: Int
    public let status: String
    public let storagePath: String

    enum CodingKeys: String, CodingKey {
        case batchId = "batch_id"
        case createdAt = "created_at"
        case id
        case physicalCardId = "physical_card_id"
        case publicUrl = "public_url"
        case side
        case sortOrder = "sort_order"
        case status
        case storagePath = "storage_path"
    }

    public init(batchId: String, createdAt: String, id: String, physicalCardId: String?, publicUrl: String?, side: String?, sortOrder: Int, status: String, storagePath: String) {
        self.batchId = batchId
        self.createdAt = createdAt
        self.id = id
        self.physicalCardId = physicalCardId
        self.publicUrl = publicUrl
        self.side = side
        self.sortOrder = sortOrder
        self.status = status
        self.storagePath = storagePath
    }
}

/// Row shape for `public.valuation_snapshots`. Generated from database.types.ts — do not edit by hand.
public struct ValuationSnapshotsRow: Codable, Sendable, Identifiable {
    public let cmTrendEur: Double?
    public let confidence: String?
    public let createdAt: String
    public let ebayAvgGbp: Double?
    public let ebayLowGbp: Double?
    public let ebaySaleCount: Int?
    public let ebaySource: String?
    public let ebayTopGbp: Double?
    public let fxDate: String?
    public let fxEurGbp: Double?
    public let fxUsdGbp: Double?
    public let id: String
    public let isCurrent: Bool
    public let physicalCardId: String
    public let snapshotVersion: Int
    public let suggestedPriceGbp: Double?
    public let tcpMarketUsd: Double?

    enum CodingKeys: String, CodingKey {
        case cmTrendEur = "cm_trend_eur"
        case confidence
        case createdAt = "created_at"
        case ebayAvgGbp = "ebay_avg_gbp"
        case ebayLowGbp = "ebay_low_gbp"
        case ebaySaleCount = "ebay_sale_count"
        case ebaySource = "ebay_source"
        case ebayTopGbp = "ebay_top_gbp"
        case fxDate = "fx_date"
        case fxEurGbp = "fx_eur_gbp"
        case fxUsdGbp = "fx_usd_gbp"
        case id
        case isCurrent = "is_current"
        case physicalCardId = "physical_card_id"
        case snapshotVersion = "snapshot_version"
        case suggestedPriceGbp = "suggested_price_gbp"
        case tcpMarketUsd = "tcp_market_usd"
    }

    public init(cmTrendEur: Double?, confidence: String?, createdAt: String, ebayAvgGbp: Double?, ebayLowGbp: Double?, ebaySaleCount: Int?, ebaySource: String?, ebayTopGbp: Double?, fxDate: String?, fxEurGbp: Double?, fxUsdGbp: Double?, id: String, isCurrent: Bool, physicalCardId: String, snapshotVersion: Int, suggestedPriceGbp: Double?, tcpMarketUsd: Double?) {
        self.cmTrendEur = cmTrendEur
        self.confidence = confidence
        self.createdAt = createdAt
        self.ebayAvgGbp = ebayAvgGbp
        self.ebayLowGbp = ebayLowGbp
        self.ebaySaleCount = ebaySaleCount
        self.ebaySource = ebaySource
        self.ebayTopGbp = ebayTopGbp
        self.fxDate = fxDate
        self.fxEurGbp = fxEurGbp
        self.fxUsdGbp = fxUsdGbp
        self.id = id
        self.isCurrent = isCurrent
        self.physicalCardId = physicalCardId
        self.snapshotVersion = snapshotVersion
        self.suggestedPriceGbp = suggestedPriceGbp
        self.tcpMarketUsd = tcpMarketUsd
    }
}
