// Parses src/db/database.types.ts (the committed, canonical `supabase gen types typescript`
// output) and emits Sources/CurioContracts/DBTypes.swift — Swift Codable structs for the same
// tables. Swift is DERIVED from the TS file in this one script, so the two artifacts cannot
// diverge: there is only one schema snapshot, read once, emitted twice.
//
// TS `number` doesn't distinguish int4 vs numeric — Postgres does. INT_COLUMNS overrides those
// specific columns to Swift `Int`; everything else numeric becomes `Double`. This map is sourced
// from the same `list_tables(verbose: true)` snapshot as database.types.ts's own regeneration —
// update both together if a column's Postgres type changes.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const INT_COLUMNS: Record<string, Set<string>> = {
  catalogue_sets: new Set(["card_count"]),
  condition_assessments: new Set(["assessment_version"]),
  physical_cards: new Set(["batch_position"]),
  profiles: new Set(["aged_inventory_days"]),
  scan_items: new Set(["sort_order"]),
  valuation_snapshots: new Set(["ebay_sale_count", "snapshot_version"]),
};

interface Field {
  name: string;
  tsType: string;
  nullable: boolean;
}

function parseRowBlock(tableName: string, src: string): Field[] {
  const tableRe = new RegExp(`\\n      ${tableName}: \\{\\n        Row: \\{([\\s\\S]*?)\\n        \\}\\n        Insert:`);
  const m = tableRe.exec(src);
  if (!m) throw new Error(`Could not find Row block for table "${tableName}"`);
  const body = m[1];
  const fields: Field[] = [];
  for (const line of body.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const fm = /^(\w+): (.+)$/.exec(trimmed);
    if (!fm) continue;
    const [, name, rawType] = fm;
    const nullable = rawType.includes("| null");
    const tsType = rawType.replace(/\s*\|\s*null\s*$/, "").trim();
    fields.push({ name, tsType, nullable });
  }
  return fields;
}

function toSwiftType(tableName: string, field: Field): string {
  let base: string;
  switch (field.tsType) {
    case "string":
      base = "String";
      break;
    case "number":
      base = INT_COLUMNS[tableName]?.has(field.name) ? "Int" : "Double";
      break;
    case "boolean":
      base = "Bool";
      break;
    case "string[]":
      base = "[String]";
      break;
    case "Json":
      base = "JSONValue";
      break;
    default:
      throw new Error(`Unmapped TS type "${field.tsType}" for ${tableName}.${field.name}`);
  }
  return field.nullable ? `${base}?` : base;
}

function toSwiftPropertyName(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function emitStruct(tableName: string, fields: Field[]): string {
  const structName = tableName
    .split("_")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
  const lines: string[] = [];
  lines.push(`/// Row shape for \`public.${tableName}\`. Generated from database.types.ts — do not edit by hand.`);
  lines.push(`public struct ${structName}Row: Codable, Sendable, Identifiable {`);
  for (const f of fields) {
    const swiftType = toSwiftType(tableName, f);
    const propName = toSwiftPropertyName(f.name);
    if (propName === f.name) {
      lines.push(`    public let ${propName}: ${swiftType}`);
    } else {
      lines.push(`    public let ${propName}: ${swiftType}`);
    }
  }
  lines.push("");
  // CodingKeys only needed when a Swift name differs from the snake_case column name.
  const renamed = fields.filter((f) => toSwiftPropertyName(f.name) !== f.name);
  if (renamed.length) {
    lines.push("    enum CodingKeys: String, CodingKey {");
    for (const f of fields) {
      const propName = toSwiftPropertyName(f.name);
      lines.push(propName === f.name ? `        case ${propName}` : `        case ${propName} = "${f.name}"`);
    }
    lines.push("    }");
    lines.push("");
  }
  lines.push(`    public init(${fields.map((f) => `${toSwiftPropertyName(f.name)}: ${toSwiftType(tableName, f)}`).join(", ")}) {`);
  for (const f of fields) {
    const p = toSwiftPropertyName(f.name);
    lines.push(`        self.${p} = ${p}`);
  }
  lines.push("    }");
  lines.push("}");
  return lines.join("\n");
}

export function generateDbTypesSwift(): string {
  const src = readFileSync(join(root, "src/db/database.types.ts"), "utf8");
  const tables = [
    "audit_events",
    "catalogue_cards",
    "catalogue_sets",
    "condition_assessments",
    "physical_cards",
    "profiles",
    "scan_items",
    "valuation_snapshots",
  ];

  const header = `// AUTO-GENERATED by scripts/gen-swift-db.ts from src/db/database.types.ts — do not edit by hand.
// Regenerate via \`npm run build\`. See README.md "Releasing a new version".

import Foundation

/// Mirrors the TS \`Json\` union for jsonb columns (payload, defects, comps, ...).
public enum JSONValue: Codable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null; return }
        if let v = try? container.decode(Bool.self) { self = .bool(v); return }
        if let v = try? container.decode(Double.self) { self = .number(v); return }
        if let v = try? container.decode(String.self) { self = .string(v); return }
        if let v = try? container.decode([String: JSONValue].self) { self = .object(v); return }
        if let v = try? container.decode([JSONValue].self) { self = .array(v); return }
        throw DecodingError.typeMismatch(JSONValue.self, .init(codingPath: decoder.codingPath, debugDescription: "Unsupported JSON value"))
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let v): try container.encode(v)
        case .number(let v): try container.encode(v)
        case .bool(let v): try container.encode(v)
        case .object(let v): try container.encode(v)
        case .array(let v): try container.encode(v)
        case .null: try container.encodeNil()
        }
    }
}

`;

  const structs = tables.map((t) => emitStruct(t, parseRowBlock(t, src))).join("\n\n");
  return header + structs + "\n";
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = generateDbTypesSwift();
  // check-drift.ts points this at a scratch dir so it can diff a fresh build against what's
  // committed, without recopying node_modules per run.
  const outDir = process.env.CURIO_CONTRACTS_OUT_DIR ?? join(root, "Sources/CurioContracts");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "DBTypes.swift"), out);
  console.log(`Wrote ${join(outDir, "DBTypes.swift")}`);
}
