// Parses src/db/database.types.ts (the committed, canonical `supabase gen types typescript`
// output) and emits src/main/kotlin/com/curio/contracts/DBTypes.kt — kotlinx.serialization data
// classes for the same shared tables gen-swift-db.ts covers. Kotlin is DERIVED from the TS file
// in this one script (same as Swift), so all three artifacts cannot diverge: one schema snapshot,
// read once, emitted three times.
//
// Row-block parsing is shared with gen-swift-db.ts — see db-types-parser.ts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { SHARED_TABLES, INT_COLUMNS, parseRowBlock, type Field } from "./db-types-parser.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function toKotlinType(tableName: string, field: Field): string {
  let base: string;
  switch (field.tsType) {
    case "string":
      base = "String";
      break;
    case "number":
      base = INT_COLUMNS[tableName]?.has(field.name) ? "Int" : "Double";
      break;
    case "boolean":
      base = "Boolean";
      break;
    case "string[]":
      base = "List<String>";
      break;
    case "Json":
      base = "JsonElement";
      break;
    default:
      throw new Error(`Unmapped TS type "${field.tsType}" for ${tableName}.${field.name}`);
  }
  return field.nullable ? `${base}?` : base;
}

function toKotlinPropertyName(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function emitDataClass(tableName: string, fields: Field[]): string {
  const className = tableName
    .split("_")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
  const props = fields
    .map((f) => {
      const propName = toKotlinPropertyName(f.name);
      const kotlinType = toKotlinType(tableName, f);
      const serialName = propName !== f.name ? `@SerialName("${f.name}") ` : "";
      const default_ = kotlinType.endsWith("?") ? " = null" : "";
      return `    ${serialName}val ${propName}: ${kotlinType}${default_},`;
    })
    .join("\n");
  return `/** Row shape for \`public.${tableName}\`. Generated from database.types.ts — do not edit by hand. */\n@Serializable\npublic data class ${className}Row(\n${props}\n)`;
}

export function generateDbTypesKotlin(): string {
  const src = readFileSync(join(root, "src/db/database.types.ts"), "utf8");
  const tables = SHARED_TABLES;

  const header = `// AUTO-GENERATED by scripts/gen-kotlin-db.ts from src/db/database.types.ts — do not edit by
// hand. Regenerate via \`npm run build\`. See README.md "Releasing a new version".

package com.curio.contracts

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonElement

`;

  const classes = tables.map((t) => emitDataClass(t, parseRowBlock(t, src))).join("\n\n");
  return header + classes + "\n";
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = generateDbTypesKotlin();
  // check-drift.ts points this at a scratch dir so it can diff a fresh build against what's
  // committed, without recopying node_modules per run.
  const outDir = process.env.CURIO_CONTRACTS_KOTLIN_OUT_DIR ?? join(root, "src/main/kotlin/com/curio/contracts");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "DBTypes.kt"), out);
  console.log(`Wrote ${join(outDir, "DBTypes.kt")}`);
}
